### ISSUE TITLE
[Proposal] Stack to have a relation to pull request

### ISSUE THREAD

**Issue by viniciusgama** [Shopify/shipit-engine#1017]
Currently stacks have many pull requests related to it but are only used by the merge request feature. We would like to propose the option for a stack to have a optional one to one relation with a PR as well. This would be helpful in cases were stacks are auto provisioned based on PR creation/update/labeling/etc and removed based on the PR being closed/unlabeled/etc. Currently we make this relation based on the environment name but we think this is suboptimal. With this we would also store information about all PRs rather than just when a merge is requested.

Would this be accepted? If so, any directions or suggestions you would like to propose?

**Comment by casperisfine** [comment]
I suppose this request is part of the @Powerhome effort to get stacks provisioned on PR opening?

If so I'm willing to consider such relation in the context of the fully working feature, but not as some kind of hidden hook for extensions.

I can't seem to find the issue or PR where we had this discussion before, but: I think the dynamically provided stack on PR opening feature is a neat idea, and I'm totally willing to merge it. However it needs to follow shipit design. Meaning it need to be relatively flexible and not just an implementation of your particular workflow.

**Comment by viniciusgama** [comment]
Sure @casperisfine . We will try to make whatever change we need on shipit itself as flexible and not tied to our use case as possible. We still want to contribute to upstream as much as we can.

We will start something and come back shortly.
