### ISSUE TITLE
Stack/Repo name script variable?

### ISSUE THREAD

**Issue by damianpursey** [Shopify/shipit-engine#1021]
I'm trying to create a mostly-portable script to be used for our deployments, and I'm not sure if I'm missing something obvious but it feels like the name of the current stack should be available as an environment variable much like `BRANCH` or `ENVIRONMENT`. If there's an obvious/consistent way to check this from within a deployment context please let me know.

**Comment by casperisfine** [comment]
What would you consider the "stack name" to be? `repo_onwer/repo_name/environment` ?

If so it's already all expose, but in chuncks:

`GITHUB_REPO_NAME`, `GITHUB_REPO_OWNER`, 'ENVIRONMENT`.

Here: https://github.com/Shopify/shipit-engine/blob/26e375c680017a86b870ecf72dbcdac1edb46a3d/app/models/shipit/stack.rb#L50-L51


I suppose we could expose the combined form as well.

**Comment by damianpursey** [comment]
I had found `GITHUB_REPO_NAME` in that section you linked, but trying it in my script I didn't get what I expected, I assumed I was incorrectly interpreting how that variable was exposed but it seems more likely now there was a different issue in my script.

I'm glad these are available, but would it be worth also mentioning them among the others in the main README? I could also create the PR if you'd like to save some time.

**Comment by casperisfine** [comment]
Yeah, we probably forgot to update the README. Documentation PRs are welcome.

**Comment by damianpursey** [comment]
I've opened a small PR here for this https://github.com/Shopify/shipit-engine/pull/1022 (Not sure how to rerun the CLA step now that I've accepted.), I've also realized that our currently deployed version of ShipIt is behind a few versions and doesn't have the changes with these variables yet, so we'll need to upgrade. Still, thanks for bringing them to my awareness.
