### ISSUE TITLE
Mysql2::Error: Data too long for column 'gzip_output' at row 1

### ISSUE THREAD

**Issue by DazWorrall** [Shopify/shipit-engine#1041]
This is while running `ChunkRollupJob`. We define this as a [binary](https://github.com/Shopify/shipit-engine/blob/1a7231047d83d6ff7a0c3309bc64f819c80d7f2b/test/dummy/db/schema.rb#L254) column in AR, which translates to a `mediumblob` MySQL type, which has a [16MB limit](https://stackoverflow.com/a/5775601). We could try to change this to `longblob`, but that has a _4GB_ limit, which is... maybe too much rope.

Wdyt @casperisfine? Should we try and fix this or instead catch the exception, log a warning and abandon rollup for these tasks? This seems to affect ~40K of our ~500K jobs.

**Comment by casperisfine** [comment]
I think we should increase the column size.

Skipping the rollup might seem tempting, but this would lead to a huge increase in the chunks table.

It's a bit crazy that we have so many deploy with over 16MB of gzipped output though. It's totally tangent, but probably worth taking a look at wether they are necessary.

**Comment by casperisfine** [comment]
After more thoughts I think I agree with you that 4GB is way too much rope, and that regardless of what limit we put, someone's going to hit it, and that we need a proper error reporting and handling in such case.
