### ISSUE TITLE
[Bug] Stack timeline page link/url goes to the task list page

### ISSUE THREAD

**Issue by ohsabry** [Shopify/shipit-engine#1083]
@DazWorrall Your change here made the tasks list what shows up when you look at a stack's timeline. probably some rails url helper magic that's easy to fix. 
https://github.com/Shopify/shipit-engine/pull/1077

![image](https://user-images.githubusercontent.com/6708158/84585553-f00dc280-adde-11ea-957e-a98ea2c571b0.png)

**Comment by DazWorrall** [comment]
Fixed, sorry about that @ohsabry.

**Comment by ohsabry** [comment]
@DazWorrall np at all, thanks for fixing it so quick
