### ISSUE TITLE
How to limit access to organisation members only

### ISSUE THREAD

**Issue by eldadvcita** [Shopify/shipit-engine#1113]
Hi,
I'm trying to evaluate Shipit for my organization. 
During the evaluation process, I noticed that non-organization members are able to access the web interface which imposes a security risk.

Is there a way to prevent access from non-organization members only?

Please advise,
Thanks!

**Comment by casperisfine** [comment]
You can either use the built in feature to limit to members of a GitHub team, see `github.oauth.teams`: https://github.com/Shopify/shipit-engine/blob/master/docs/setup.md

Or simply implement any authentication method you like in your rails app, e.g. Google Auth, SAML, etc.
