### ISSUE TITLE
How to merge queue is triggered

### ISSUE THREAD

**Issue by eldadvcita** [Shopify/shipit-engine#1114]
Hi,
We are trying to evaluate Shipit. By reading several blog posts, we noticed that the merge queue is something the can be customized.
By reviewing the documentation on this repository, I wasn't able to find such configurations. For example:
- Trigger merge queue on a given interval
- Trigger merge queue after X pull requests are pending 
- etc

Please advise,
Thanks!

**Comment by casperisfine** [comment]
The merge queue is based on webhooks. It merges the PRs in the queue when the commit status requirements are met (e.g. greem ci). https://github.com/Shopify/shipit-engine#merge-queue
