### ISSUE TITLE
Guidance and suggestions for take shipit forward to Merge Queue v2

### ISSUE THREAD

**Issue by David-Vaknin-Vcita** [Shopify/shipit-engine#1115]
Hi all,

We are planning to expand Shipit capabilities towards the Merge Queue v2 (https://engineering.shopify.com/blogs/engineering/successfully-merging-work-1000-developers)
We want to get any recommendations on how and what is the best way to do that.

The missing capabilities are:
* Use "predictive branch to merge a batch of PR's."
* Custom "merge.require" instead of using only for statuses context 
* Adding failure mechanism for a batch of PR's

I really appreciate any help you can provide.

**Comment by casperisfine** [comment]
v2 is an entirely different project, and isn't open source, at least not now, see: https://github.com/Shopify/shipit-engine/issues/956

I'm afraid I can't help you.
