### ISSUE TITLE
Build a CI process for shipit (build and tests)

### ISSUE THREAD

**Issue by David-Vaknin-Vcita** [Shopify/shipit-engine#1126]
Hi all, 
I'd like to get some help and info about the shipit engine build process.
My goal is to **build a CI process for shipit build and tests**.

Following that, two main questions: 
1. Can someone provide me instructions and info about the process?
2.  what is the build standard in case of:
- Prerequisite
- Bundler
- Dockerfile
- OS
- How to run unit-test
-CI
- unit-tests
etc.

I really appreciate any help.

**Comment by casperisfine** [comment]
You can simply look at the github actions definitions, but really it's mostly like any Rails app. https://github.com/Shopify/shipit-engine/blob/master/.github/workflows/main.yml
