### ISSUE TITLE
Renaming the branch for a stack

### ISSUE THREAD

**Issue by bspellacy** [Shopify/shipit-engine#1129]
### Context
We're in the process of renaming our base branches from `master` to `main` at Patch. The final blocker for us to to ensure our deployments - which are managed by shipit - aren't blocked. Additional context from Github can be found [here](https://github.com/github/renaming).

### Question
What's the best way to go about changing which branch to use for a shipit stack?

Based on my current understanding we can:
- Delete the stack and recreate it
  - This isn't ideal because we lose past deploy/task data
- Hop into rails console in production and update the stack's branch name
  - Will this work if I just update the branch name? Or is there something else I should be doing?

Any context or experience that you can share would be appreciated, thank you!

**Comment by casperisfine** [comment]
You pretty much said it all. The Shipit UI doesn't allow to change the branch because if you were to change it for a radically different branch it would cause quite a mess. But if you change it for an alias then it will work fine.
