### ISSUE TITLE
[Proposal] Plugin-based Git solutions support

### ISSUE THREAD

**Issue by meme** [Shopify/shipit-engine#1134]
> In response to: https://github.com/Shopify/shipit-engine/issues/460 and https://github.com/Shopify/shipit-engine/issues/462

Instead of explicitly adding support for every Git provider under the sun, decouple from GitHub and extract it into an in-tree plugin which provides optional capabilities like commit updates, user information and commit statuses.

When integration with a new Git provider is needed, an out-of-tree plugin is written that implements the subset of supported features.

This means that the interface between Shipit and these plugins needs to remain stable or maintain an API contract.

**Comment by casperisfine** [comment]
> This means that the interface between Shipit and these plugins needs to remain stable or maintain an API contract.

That's not something we're willing to support. Sorry.

**Comment by meme** [comment]
I plan to work on this. There is no chance of accepting any part of this upstream?

**Comment by casperisfine** [comment]
No sorry. The layer of indirection to be able to implement this kind of plugins means too much code churn and extra code complexity for no benefits.

You are welcome to fork the project though.
