### ISSUE TITLE
Rails 6 needs sass-rails v6

### ISSUE THREAD

**Issue by saiqulhaq** [Shopify/shipit-engine#1197]
https://github.com/Shopify/shipit-engine/blob/9bd39a2496175c62395ecf35b5ae95c776dc896b/shipit-engine.gemspec#L41

on template.rb, it refers to shipit on rubygems, which still has dependency to rails 5

**Comment by casperisfine** [comment]
No https://rubygems.org/gems/sass-rails/versions/5.1.0, sass-rails has a `>=` dependency on Rails.

We're running shipit with Rails 6.1, and even CI does it.

We should relax this dependency regardless, but you can already run Rails 6.1.

**Comment by saiqulhaq** [comment]
I executed this command 
```
rails _6.1_ new shipit --skip-action-cable --skip-turbolinks --skip-action-mailer --skip-active-storage --skip-webpack-install --skip-action-mailbox --skip-action-text -m https://raw.githubusercontent.com/Shopify/shipit-engine/master/template.rb
``` 
it failed on `bundle install` step

**Comment by batasrki** [comment]
@casperisfine I have the same issue as @saiqulhaq. Using the latest release as well as the master branch, the `bundle install` step fails with mismatched dependencies.

```
