### ISSUE TITLE
Github Private key error: OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error

### ISSUE THREAD

**Issue by kevinpolar** [Shopify/shipit-engine#1238]
Hi,

I'm trying to deploy a shipit instance in our environment on GCP using kubernetes

The particular error I'm having is in this line of code: `key = OpenSSL::PKey::RSA.new(private_key)` in the github_app.rb when trying to run the teams:fetch command.

I've placed the private key in a kubernetes secret, the actual value that was encoded to base64 had new line as a string `\\n`(double back slash for escape char) in it.
Upon checking via the rails console, the private key being set in the Shipit.github and the Rails.application.secrets has spaces in between them, see the screenshot below:
<img width="596" alt="Screen Shot 2021-12-21 at 4 38 17 PM" src="https://user-images.githubusercontent.com/15812290/146900043-281cc7af-d335-43e1-8968-70e1ee04d90d.png">

I did some testing, I tried manually running the `OpenSSL::PKey::RSA.new(Rails.application.secrets.github[:private_key])` and I did indeed get the same error. Now I also tried running the same command but supplying my private key with the `\n` in the actual string and it worked.
<img width="375" alt="Screen Shot 2021-12-21 at 5 13 53 PM" src="https://user-images.githubusercontent.com/15812290/146903915-88c83263-39d9-4a91-a321-35a36254ae50.png">

**Comment by kevinpolar** [comment]
ah well, I do have the new lines in the values, in the secrets, but when it goes to the app, in the secrets, it changes into white spaces.

**Comment by casperisfine** [comment]
Our yaml is like this:

```yaml
private_key: "-----BEGIN RSA PRIVATE KEY-----\nMIIE....
```

To generate it properly I recommend to use:

```ruby
puts File.read("<path/to/key>").to_yaml
```

**Comment by casperisfine** [comment]
> checking the env variable

Oh, you pass it through an env var? Do you interpolate it in the YAML or something? If so you might need a `to_yaml` to make sure newlines and such are escaped.
