### ISSUE TITLE
Setup instructions outdated

### ISSUE THREAD

**Issue by bouk** [Shopify/shipit-engine#1256]
Hi there,

Tried to follow the [setup instructions](https://github.com/Shopify/shipit-engine/blob/master/docs/setup.md) and ran into some issue:

1. The instructions say to install version 6.1 of Rails, but the template.rb requires `>= 7.0`
2. After changing instructions to use `7.0.2` I get the following: 
<img width="703" alt="image" src="https://user-images.githubusercontent.com/97820/158213892-466579bc-64d6-4012-9097-ce9c21c15075.png">

I assume this is because a new release of shipit-engine needs to be cut with the constraints updated.

**Comment by casperisfine** [comment]
Yeah, I only did the Rails 7 upgrade last week and still need to cut a new release.

You can work around this by editing the `Gemfile.lock` and point to `shipit-engine`'s `master` branch.

I'll try to cut a new release this week.
