### ISSUE TITLE
Deployment status not updating in GitHub

### ISSUE THREAD

**Issue by pcothenet** [Shopify/shipit-engine#1311]
Hi team shipit! Thanks a lot for your great work on this tool! 

Since last week, our shipit instance isn't updating the status of the `deployment` in GitHub anymore.

The deploys are still working as expected:
<img width="1218" alt="Screenshot 2023-07-03 at 9 57 05 AM" src="https://github.com/Shopify/shipit-engine/assets/1460006/92ac0d12-8a9f-4a98-ad66-80cf56d43830">

Yet, the Deployment status stays in "Pending" in GitHub:
<img width="1315" alt="Screenshot 2023-07-03 at 9 17 12 AM" src="https://github.com/Shopify/shipit-engine/assets/1460006/a84f80fd-c25c-42a0-a2aa-d8a21d539d39">

- All webhooks are being received and acted on properly.
- The deployment gets created properly in GitHub, so we don't think it is a deployment issue.

In logs, we can see the following error, with a timing corresponding to the end of a deploy.
```
Couldn't find template for digesting: statuses/status
```

Things we have tried so far that haven't helped:
- Recreating the stack in shipit
- Deleting the environment in GitHub
- Resetting the git cache

Another thing of note is that the issue started happening at the same time as the big GitHub outages of last week, and also correlates with some instability of our shipit hosting.

Any ideas what might be causing this and how to fix it?

**Comment by benlangfeld** [comment]
Credit goes to @ryanmrodriguez for tracking this one down.
