### ISSUE TITLE
[Documentation] Breaking change in 0.39.0: switch from secrets to credentials

### ISSUE THREAD

**Issue by davidcornu** [Shopify/shipit-engine#1366]
While upgrading our instance from `0.38.0` to `0.39.0` we had to switch from using Rails secrets to credentials because of this change (https://github.com/Shopify/shipit-engine/pull/1326/files#diff-b2e066ed79ba733982401273e1c6373dbd28c3e3b9ebf62482b5c31c7bbdf3fcR294) where Shipit switched from using `Rails.application.secrets` to `Rails.application.credentials`.

I would recommend documenting this in the release notes for `0.39.0` so others making the same upgrade know about it ahead of time.

**Comment by casperisfine** [comment]
Yeah, `Rails.application.secrets` were unfortunately deprecated, so we had to migrate over. Changelog is a good call.

**Comment by casperisfine** [comment]
Hum, actually it is already in the release notes:

```
* Migrate from legacy Rails secrets to credentials (#1326)
  * Rails secrets were [deprecated in Rails 7.1](https://github.com/rails/rails/pull/48472)
  * [Guide on credentials](https://guides.rubyonrails.org/security.html#custom-credentials)
```
