### ISSUE TITLE
Disparate Ruby Versions

### ISSUE THREAD

**Issue by Phillita** [Shopify/shipit-engine#1371]
Hello ShipIt Team!

First off, thank you for your commitment to OSS. 

I've run into an issue during the setup of the ShipIt project. I've initiated the repo with Ruby 3.1 and went through the setup steps. All was going well until I tried to deploy a test application. This application runs on Ruby 3.4. I get the following error at the bundle step:

![Image](https://github.com/user-attachments/assets/d2dd2316-1cde-47b3-a635-1be9f170f3a6)

I've tried running a setup using the shipit.yml where I set the Ruby version in the `dependencies.pre` and overrode using the `dependencies.override` and have had no luck getting past this issue. Below is me trying to run the install by installing/setting the version before the bundle install:

![Image](https://github.com/user-attachments/assets/3f751c56-99ce-4afc-8de6-e111e23cd167)

Unfortunately, many projects won't have the same version as the ShipIt project. Can ShipIt detect/install/use the Ruby version from the project it is trying to deploy? I'm likely doing something wrong.

**Comment by casperisfine** [comment]
> my Unix system

What system is that?

**Comment by casperisfine** [comment]
I just tried it and it's indeed broken, I suppose `sed` changed on OSX a while ago.

I think we should change it for `/usr/bin/sed -i '' '/^ruby /d' Gemfile`

**Comment by Phillita** [comment]
Tested on my end and that works as expected!
