### ISSUE TITLE
Message box needs a proper design

### ISSUE THREAD

**Issue by EiNSTeiN-** [Shopify/shipit-engine#173]
Assigned to @vernalkick 

![f7fb56dc-f666-11e3-8fd4-ffbe1e070269](https://cloud.githubusercontent.com/assets/2053039/3314550/1719863e-f6f2-11e3-843f-ef5d9380307d.png)

**Comment by gmalette** [comment]
This has been addressed in the new design, reopen if it's unsatisfactory
