### ISSUE TITLE
CCMenu support

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#347]
Some people are using CCMenu to know the state of master, so they don't merge in master if the CI is red.

Since stacks on Shipit can aggregate multiple CIs, and that it is also recommended not to merge when the stack is locked, a CCMenu.xml endpoint would be nice.

Travis-CI support as example http://docs.travis-ci.com/user/cc-menu/

cc @cjoudrey @JakeCataford

**Comment by davidcornu** [comment]
@byroot I really want this. 

> The url with the access token would be freely accessible from the settings page of each stacks.

Should each user have a token for each stack?

**Comment by byroot** [comment]
One token per use should enough I think.

**Comment by edward** [comment]
Please yes still relevant

**Comment by DazWorrall** [comment]
Rev 1 of this is on the way: #659

**Comment by DazWorrall** [comment]
@edward @davidcornu @gmalette this has been deployed, you can get the URL from a stack's settings page - give it a try and let us know what you think.

**Comment by edward** [comment]
@DazWorrall here’s the error that I’m running into:

![image](https://cloud.githubusercontent.com/assets/325/23222435/dd41f79e-f8f5-11e6-81ca-6541c648d3a6.png)

**Comment by DazWorrall** [comment]
@edward you have to pick 'Use URL as entered above' - does that work?

**Comment by edward** [comment]
That’s it! SO NICE THANK YOU

I’ll make a PR for being more descriptive with CCMenu setup.

**Comment by DazWorrall** [comment]
@edward do give us some feedback after you've used it for a little while, hopefully it behaves as you expect :)

**Comment by edward** [comment]
Looks great so far!
