### ISSUE TITLE
Remove the dependency on EventMachine

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#348]
Because of pubsubstub, thin is pretty much the only usable webserver.

We should either make that dependency explicit, or find a suitable way to run Shipit with another webserver. Ideally without losing the UI refresh feature.

I propose we start by adding thin in the gemspec, so that at least it's functional in development.

**Comment by byroot** [comment]
@gmalette should I close this?

**Comment by gmalette** [comment]
Did you want me to remove EM altogether? This could still cause problems due to native extensions.

**Comment by byroot** [comment]
Nah I was simply wondering if your update of pubsubstub fixed this or not. You tell me :)

**Comment by gmalette** [comment]
Well, it did remove the dependency on Thin. I'll change the message

**Comment by byroot** [comment]
We're testing https://github.com/gmalette/pubsubstub/pull/9 in production. All is going well so far, I'll update the pubsubstub dependency if no issue if found until next week.

**Comment by gmalette** [comment]
We just have to make sure we don't break installations that are currently on EM. At worse they should get  polling like we did previously with other servers

**Comment by byroot** [comment]
Good point

**Comment by casperisfine** [comment]
This was fixed a while ago.
