### ISSUE TITLE
New stack with only 1 commits shows no undeployed commits.

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#356]
As we just figured out, `stacks#show` will filter commits with `id` greater than the last dpeloyed commit.

and `Stack#last_dpeloyed_commit` will default to the first commit of the stack is there is no deploy records.

Both combined mean that a stack with only one commit and no deploy records won't show any commit.

cc @EmilS

**Comment by jules2689** [comment]
This PR breaks initial deploys.
`deploy_controller` calls `last_deployed_commit` and ends up returning this: `ActiveRecord::AssociationTypeMismatch (Commit(#70029418532760) expected, got Module(#70029391563920)):`

Will look at a fix.

**Comment by jules2689** [comment]
https://github.com/Shopify/shipit-engine/pull/569 should fix it. Not sure if the best solution. Seems to be the only case where a module won't do though.
