### ISSUE TITLE
task notifications have the wrong text

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/shipit-engine#367]
When you run a custom task (such as restart), the chrome notification has the wrong text:

![monosnap 2015-05-21 07-58-21](https://cloud.githubusercontent.com/assets/118850/7748099/79bfb05a-ff8f-11e4-89eb-c2c10644f75f.png)

**Comment by byroot** [comment]
Fixed a while ago, thanks.

**Comment by dwradcliffe** [comment]
Still not fixed with latest code

**Comment by davidcornu** [comment]
Just checked https://github.com/Shopify/shipit-engine/blob/2ee8b0346125afcab3cd5f447e014cb7d6472b15/app/assets/javascripts/task/notifications.js.coffee.erb. All the copy is for deploys.

**Comment by byroot** [comment]
Yeah I misunderstood the issue.

**Comment by byroot** [comment]
Properly fixed in 6b8a4207274b4acf5a1c354fbcfe907c7f8cf786
