### ISSUE TITLE
"back to top" button

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/shipit-engine#382]
Some deploys have VERY long output. I would like a "back to top" button somewhere so I don't have to scroll for 5 minutes to get back to the top navigation.

Or maybe there's a better way to address this with the UI changes? @funionnn

**Comment by funionnn** [comment]
Good call, we can add a 'back to top'

**Comment by byroot** [comment]
Once https://github.com/Shopify/shipit-engine/issues/382 is merged, we'll have a sticky header on deploy, so we can easily add that back to top button.

**Comment by byroot** [comment]
> scroll for 5 minutes to get back to the top navigation.

Just to be sure, you asked the back to top so you could reach the header navigation? If so doeshttps://github.com/Shopify/shipit-engine/pull/550 solves your issue @dwradcliffe ?

**Comment by dwradcliffe** [comment]
Yep, that should do it, thanks!
