### ISSUE TITLE
Safari downloads an empty attachment when hitting etags

### ISSUE THREAD

**Issue by gmalette** [Shopify/shipit-engine#386]
#dunnolol 
@vernalkick

**Comment by byroot** [comment]
Here's the only reference of that issue I could find: http://apple.stackexchange.com/questions/152587/unknown-file-download-after-reload-in-safari-8-0-on-os-x-yosemite

Unfortunately no solution is provided. I also confirm that it doesn't happen only in dev...

I guess we could not use the cache when the user agent is safari, but that is very ugly, and who use Safari anyway?

**Comment by vernalkick** [comment]
> who use Safari anyway?

Me.

**Comment by byroot** [comment]
:trollface:

**Comment by byroot** [comment]
Couldn't repro with Safari 9. I assume they fixed it.
