### ISSUE TITLE
Delete... misguiding in stack

### ISSUE THREAD

**Issue by gmalette** [Shopify/shipit-engine#399]
![screen shot 2015-05-22 at 3 52 36 pm](https://cloud.githubusercontent.com/assets/351915/7778553/9ab3670a-009a-11e5-8b41-5b00ff782d7a.png)

It makes you think there will be a confirmation step, but no, it simply deletes the stack lol

**Comment by byroot** [comment]
We should probably have a confirmation page for this. To explain what will actually be deleted.

**Comment by byroot** [comment]
Actually @etiennebarrie just figured out that this button have a `data-confirm`. So we can either have a nice confirmation page, bringing rails-ujs back could be an okish fix too.

**Comment by byroot** [comment]
Fixed in https://github.com/Shopify/shipit-engine/commit/890d8c0d756840e2673b4c04dbb76f7dbb6e4bc7
