### ISSUE TITLE
Current design can't acomodate more than 2 or 3 custom tasks

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#411]
Custom tasks buttons can easily go off screen and create an horizontal scroll.

According to @gmalette, @funionnn and @vernalkick original plan was to go for a dropdown if the task has more than a handful tasks.
- [ ] Improve seeds so that it's easily reproducible 
- [ ] Fix the design.

Maybe @jeromegn can help? ;)

**Comment by funionnn** [comment]
Can someone include a screenshot?

**Comment by byroot** [comment]
Screenshot of the issue
![capture d ecran 2015-06-01 a 09 48 32](https://cloud.githubusercontent.com/assets/44640/7914503/778cb832-0845-11e5-8007-8cbe1036f62d.png)


Mockup by @vernalkick 
![](https://s3.amazonaws.com/f.cl.ly/items/0k3j233h333O402Y1O2l/Image%202015-06-01%20at%2010.01.42%20AM.png)

**Comment by casperisfine** [comment]
This was fixed a long time ago.
