### ISSUE TITLE
Error when polling for events on stack page

### ISSUE THREAD

**Issue by alexcoco** [Shopify/shipit-engine#415]
@byroot @gmalette 

I keep getting errors in the console and new commits never show up without a refresh.

Getting this on Chrome 43.0.2357.81 (64-bit)

![screen_shot_2015-06-01_at_1_16_08_pm](https://cloud.githubusercontent.com/assets/898172/7918869/8f833872-0862-11e5-876c-0bdeafecaf8b.png)

**Comment by gmalette** [comment]
yeah I'll look at it tonight

**Comment by gmalette** [comment]
I'm not sure if this has anything to do with the latest version of https://github.com/gmalette/pubsubstub . However I found that the scrollback doesn't work without EM, so I'll fix that too

**Comment by byroot** [comment]
I think the console errors are a red herring. The javascript was broken following the redesign, I think 71407fbe8bfe84a5b271f86143776799f3c0f8d2 will fix it.

Closing, please re-open if the bug is still here in a couple hours.

**Comment by gmalette** [comment]
Will you re-upgrade Pubsubstub ?

**Comment by gmalette** [comment]
Nevermind ;)
