### ISSUE TITLE
use "committed" instead of "merged" when it's not a merge

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/shipit-engine#425]
For commit items that aren't merge commits, it would be nice if the UI displayed "committed" instead of "merged".

![shipit - rubygems org 2015-06-08 23-23-33](https://cloud.githubusercontent.com/assets/118850/8050086/709bbe92-0e35-11e5-99a7-72c4e8f873a0.png)

**Comment by byroot** [comment]
Good point. We kinda miss the info though, expect if we consider that everything that isn't a PR merge commit is a regular commit.

**Comment by pushrax** [comment]
How about "pushed"?

**Comment by gmalette** [comment]
"" may also work. the word seems superfluous

**Comment by dwradcliffe** [comment]
Yeah I think we could just remove the word
