### ISSUE TITLE
Add support for Github Entreprise

### ISSUE THREAD

**Issue by mathieugagne** [Shopify/shipit-engine#430]
Hey guys

The company I work at has a private Github Entreprise. How can I point Shipit to a different Github instance?

Thanks

**Comment by byroot** [comment]
Of course. You just have to set `github_api.api_endpoint` in the `secrets.yml`.

I'll let this open because it means we should update the documentation.

**Comment by mathieugagne** [comment]
I'm still being redirected to github.com for authentication.

Seems omniauth-github is not set to take extra parameters needed for Github Entreprise.

From https://github.com/intridea/omniauth-github#github-enterprise-usage
```
provider :github, ENV['GITHUB_KEY'], ENV['GITHUB_SECRET'],
    {
      :client_options => {
        :site => 'https://github.YOURDOMAIN.com/api/v3',
        :authorize_url => 'https://github.YOURDOMAIN.com/login/oauth/authorize',
        :token_url => 'https://github.YOURDOMAIN.com/login/oauth/access_token',
      }
    }
```

Current implementation in [lib/shipit/engine:25](https://github.com/Shopify/shipit-engine/blob/f14cfc401273df52f2e57e96c0e0fc9a67dd8868/lib/shipit/engine.rb#L25)
```
app.middleware.use OmniAuth::Builder do
  provider(:github, Shipit.github_oauth_id, Shipit.github_oauth_secret, scope: 'email')
end
```

Seems we need an additional parameter for login or a way to grab the login url, e.g.
```yml
github_api:
  api_endpoint: 'https://github.YOURDOMAIN.com/api/v3/'
  login_endpoint: 'https://github.YOURDOMAIN.com/'
```
Other implementation could use /api/v3 by default, or have a api_version 'v3' param instead.

**Comment by mathieugagne** [comment]
Tested on a fork and worked with hardcoded `:site`, `:authorize_url` and `:token_url`

**Comment by byroot** [comment]
Yeah we need to add support for this in the `secrets.yml`. Also the links to gtihub will be broken.

I'm fixing this right away.

**Comment by mathieugagne** [comment]
Tracking a few 'github.com' mentions:
https://github.com/Shopify/shipit-engine/blob/master/app/views/stacks/new.html.erb#L11

[stacks/_header](https://github.com/Shopify/shipit-engine/blob/master/app/views/stacks/_header.html.erb#L28) link points to a github.com repository

**Comment by byroot** [comment]
@mathieugagne there is also the git url:

```ruby
  def repo_git_url
    "git@github.com:#{repo_owner}/#{repo_name}.git"
  end
```

How does that work with enterprise? It's `git@your-install.com:` ?

**Comment by mathieugagne** [comment]
@byroot Yes exactly. The `github.YOURDOMAIN.com` would replace `github.com`
