### ISSUE TITLE
How to configure CI?

### ISSUE THREAD

**Issue by mathieugagne** [Shopify/shipit-engine#435]
I got a stack and I'm getting the following error message:
"This stack is not configured for CI, but it currently requires a passing build to be able to deploy a commit.
You can either configure CI yourself, or ignore CI and deploy any commits you want."

Looking in the docs and the stack's settings, I can't find a way to configure our CI.

Any pointers?

Thanks

**Comment by byroot** [comment]
Any CI would do. It listen to GitHub status API. Alternatively you can disable the CI requirement.

**Comment by mathieugagne** [comment]
I definitely want CI integration but wasn't aware of Github status API. Would be worth mentioning in the docs.
I'll take a look at how I can get our CI to communicate its status at the end of each build.

**Comment by byroot** [comment]
Hum, good point. that error message should point to the Status API documentation.

**Comment by byroot** [comment]
I think https://github.com/Shopify/shipit-engine/commit/94cca84aced0d534652b4e837ea38b5fb20ad9fb should solves this issue.

Thanks!

**Comment by mathieugagne** [comment]
:+1:
