### ISSUE TITLE
Setup / Installation help

### ISSUE THREAD

**Issue by lanceblais** [Shopify/shipit-engine#439]
I'm trying to set up ShipIt for my team and I'm not versed in Rails.

I installed Ruby using this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-on-ubuntu-12-04-lts-precise-pangolin-with-rvm

That was fine, then I ran `rails new shipit -m https://raw.githubusercontent.com/Shopify/shipit-engine/master/template.rb` which worked as well.

Entered the github keys, no problems.

How do I configure MySQL and Redis? 

How do I run ShipIt in the "production" configuration mode?

Does it need some sort of webserver like Apache/NGINX? 

If I wanted to stick ELB in front of it, would I need to worry about long running requests (more than 60 seconds)?

Last question -- Is there anyway that maybe you can get a 1-click Heroku / AWS Elastic Beanstalk / Docker installation? Would REALLY help for people like me who don't manage Rails apps.

Also, is this the best way to ask these questions? -- I saw no IRC or contact info

**Comment by byroot** [comment]
It's true that deploying a Rails app can be tricky if you have no experience at all with that stack. There is a DO tutorial there: https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma but TBH it's kind of messy.

> Does it need some sort of webserver like Apache/NGINX?

It's better yes.

> If I wanted to stick ELB in front of it, would I need to worry about long running requests (more than 60 seconds)?

Shipit use ServerSentEvents which mean long running requests, but have no problem reconnecting if they are closed by something.

>  Is there anyway that maybe you can get a 1-click Heroku / AWS Elastic Beanstalk / Docker installation?

IIRC @arthurnn had a docker image for shipit. @arthurnn would that be production ready?

**Comment by gmalette** [comment]
Arthur's Docker image is here https://github.com/arthurnn/shipit_docker . I think he said he had gotten it to work

**Comment by lanceblais** [comment]
You're all awesome.

I'll try out the container.

Thanks!

**Comment by gmalette** [comment]
Please let us know how it's going, there's definitely room for improvement on the doc

**Comment by arthurnn** [comment]
docker should be production ready.. I did a few tests locally and in a fresh DO instance. it worked for me.

**Comment by byroot** [comment]
Closing this assuming it's solved.
