### ISSUE TITLE
If CI is retried auto deploy can be triggered twice

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#445]
Reported by @dwradcliffe 

For some reason Travis ran the test twice for https://github.com/rubygems/rubygems.org/commit/09bc5ec42204e31d67085962a9d81778fab85ac8 (and the following commits), as a result the status timeline was `pending` -> `success` -> `pending` -> `success`, see: https://api.github.com/repos/rubygems/rubygems.org/commits/09bc5ec42204e31d67085962a9d81778fab85ac8/statuses

Shipit got confused and deployed the commit twice:

![shipit-bug](https://cloud.githubusercontent.com/assets/44640/8478575/4dfdc1dc-20a0-11e5-850f-da6e0bb892a8.png)

Autodeploy should simply bail out of the newly successful commit is already deployed.

**Comment by gmalette** [comment]
lol yeah that happens on circle if someone pushes a branch with the same HEAD as master

**Comment by gmalette** [comment]
maybe the same with travis

**Comment by byroot** [comment]
Reported to Travis: https://github.com/travis-ci/travis-ci/issues/4176

**Comment by byroot** [comment]
@gmalette not it's even weirder, look at the API response, all the statuses are reported for the same build, it's not someone that branched out.

**Comment by gmalette** [comment]
oh shit yeah

**Comment by byroot** [comment]
But you're right. The issue you mention would have the same effect. But it's an easy bug to fix in the autodeploy code though.

**Comment by gmalette** [comment]
Yeah, autodeploy has to be fixed, but whether we track status change after a success is debatable

**Comment by byroot** [comment]
> whether we track status change after a success is debatable

We already had that debate, and I don't think we should discard any "CI" statuses. e.g: imagine a security audit CI, your commit is green, a vulnerability is reported, you retry, it should go red.

**Comment by gmalette** [comment]
My thoughts too

**Comment by byroot** [comment]
Fixed in #446
