### ISSUE TITLE
new stack UI needs a little love

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/shipit-engine#448]
The repo field on the new stack page has line breaks that are not pretty:

<img alt="shipit 2015-07-03 11-10-42" src="https://cloud.githubusercontent.com/assets/118850/8501521/4a4fefb8-2174-11e5-8448-f79e28d0a99d.png">

**Comment by davidcornu** [comment]
<img width="652" alt="screen shot 2015-07-06 at 9 36 34 am" src="https://cloud.githubusercontent.com/assets/325821/8523300/87a6e498-23c2-11e5-9879-e5041c5b4ddc.png">

The rest of the form needs some love too. IMHO the help text looks like a misplaced label and the checkbox for skipping CI should be on the other side.

**Comment by dwradcliffe** [comment]
This was fixed a while ago.
