### ISSUE TITLE
Abort and Rollback button

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#449]
### Context:

Shipit have been built around the idea that the deploy scripts are transactional, meaning that if you abort the script, it will go back to it's previous step like capistrano 2 used to do.

Unfortunately in real life not all deploy scripts are transactional.

### Proposal

If we acknowledge this fact, then it makes sense to have an `Abort and rollback` button on the deploy log page. It would kill the current deploy, trigger a rollback, and redirect the user to the rollback log.

The benefit would be a faster reaction in case of deploy related outages.

@gmalette thoughts?

cc @KnVerey

**Comment by gmalette** [comment]
fuck yes, but it should be only if the stack `supports_rollback?`, otherwise just abort?

**Comment by byroot** [comment]
Yes. IMO we always keep abort. And then "deploy and rollback" criteria would be: `is a deploy or is a rollback and stack.supports_rollback?`

**Comment by gmalette** [comment]
you'd allow rollbacking rollbacks?

**Comment by byroot** [comment]
Sure why not?

**Comment by gmalette** [comment]
I find it surprising. What's the outcome of rollbacking a rollback? Are you 1 step further down the rollback chain, or are you redeploying the rollbacked deploy?

**Comment by byroot** [comment]
Actually nevermind. We already don't allow to rollback rollback.
