### ISSUE TITLE
Github status querying

### ISSUE THREAD

**Issue by gmalette** [Shopify/shipit-engine#450]
Sometimes when Github is having slowdowns, people ask why Shipit is broken and not picking up their changes. Github Status has an API that we can use. We could display a status message to tell people something's going on

https://status.github.com/api/last-message.json

```json
{
"status": "minor",
"body": "We're continuing to process a significant webhook backlog. We'll maintain yellow status until the queues have drained.",
"created_on": "2015-07-06T23:02:55Z"
}
```

**Comment by davidcornu** [comment]
Could we do this in js?

**Comment by gmalette** [comment]
> Could we do this in js?

Yes. They probably support CORS, they definitely support jsonp

Should we do this in JS?

**Comment by byroot** [comment]
Since we already have crons running. I think a 5 minutesish call from a wroker that sets this in `Rails.cache` should do.

**Comment by byroot** [comment]
Also we need to disable this for Enterprise users.

**Comment by davidcornu** [comment]
> Should we do this in JS?

Would avoid additional rails logic for a presentation concern. Either way is fine though.

**Comment by gmalette** [comment]
I don't think it's a presentation concern; we could also have this for the API

**Comment by byroot** [comment]
Fixed in https://github.com/Shopify/shipit-engine/pull/605
