### ISSUE TITLE
Sticky header on the deploy page causes jumpiness

### ISSUE THREAD

**Issue by davidcornu** [Shopify/shipit-engine#452]
![2015-07-08 14_37_00](https://cloud.githubusercontent.com/assets/325821/8578802/e992d3de-257e-11e5-9a69-f1e9fa5de495.gif)

When scrolling past the sticky threshold, the text underneath jumps up.

**Comment by byroot** [comment]
The sticky header is gone as of https://github.com/Shopify/shipit-engine/pull/560

Closing this.
