### ISSUE TITLE
Support for other Git hosting solutions

### ISSUE THREAD

**Issue by cmckni3** [Shopify/shipit-engine#460]
Are there any plans to support other Git solutions, such as, GitLab, Gogs, and BitBucket?

I am mostly interested in GitLab support. I know GitLab doesn't support some of the features of GitHub e.g. Deployments but I'm willing to work on implementing it.

**Comment by byroot** [comment]
> Are there any plans to support other Git solutions, such as, GitLab, Gogs, and BitBucket?

No, there is even a tacit consensus we won't do it. We started Shipit with the idea that it was a GitHub app, not even a git one. All the data Shipit collect is fetched through the GitHub API / WebHooks and not by reading the git repo.

This shortcut really simplified things. And I'm afraid trying to support multi backends would complicate the codebase a lot.

If you need BitBucket / Gitlab support, [Zendesk's Samson](https://github.com/zendesk/samson) might suits your needs.

**Comment by cmckni3** [comment]
Thanks for the suggestion! I will check it out.

**Comment by byroot** [comment]
Apologies, @gmalette just pointed out that Samson is also tied to GitHub. Sorry :/
