### ISSUE TITLE
Samples of shipit.yml

### ISSUE THREAD

**Issue by jsegura** [Shopify/shipit-engine#463]
In the readme there is a link to `Free Samples`. Could you provide some examples?

**Comment by gmalette** [comment]
Oh snap. We'll add one. In the meantime, you can refer to [rubygems.org's `shipit.yml`](https://github.com/rubygems/rubygems.org/blob/master/shipit.yml)

What type of app are you deploying? What would help you best?

**Comment by dwradcliffe** [comment]
Also an example for heroku: https://github.com/rubygems/rubygems-status/blob/master/shipit.yml
