### ISSUE TITLE
Differentiate ignored builds

### ISSUE THREAD

**Issue by davidcornu** [Shopify/shipit-engine#466]
<img width="666" alt="screen shot 2015-07-31 at 10 31 19 am" src="https://cloud.githubusercontent.com/assets/325821/9009469/665f2690-376f-11e5-978c-da9f7a6d9e57.png">

Not sure what's going on here

**Comment by gmalette** [comment]
Can you elaborate?

**Comment by davidcornu** [comment]
If all the builds aren't complete, the build status should not be a green checkbox

**Comment by gmalette** [comment]
[`ci/circleci`](https://github.com/Shopify/shopify/blob/f6a4aea84f7f5873656ee4410470b3864171ee39/shipit.yml#L3) is ignored from the build results, so we're left with a single green status

**Comment by davidcornu** [comment]
> `ci/circleci` is ignored from the build results, so we're left with a single green status

Ah. So we should probably show that visually to avoid confusion. Maybe reduce the opacity of ignored builds or add `(ignored)` after the service name.

**Comment by gmalette** [comment]
Good idea
