### ISSUE TITLE
capistrano hangs over ssh password

### ISSUE THREAD

**Issue by mathieugagne** [Shopify/shipit-engine#468]
Thanks again for the great app. I'm almost there.. just can't get Shipit to deploy.

_Problem:_
When I start a deploy through the app it hangs when trying to `ssh` to the remote host during a capistrano deployment.
It sits there quietly waiting for me to put my ssh password even though I have ssh keys setup.

I can ssh to the host I want to deploy to from the console on my shipit box.
I can run a deploy using capistrano from the console on my shipit box.
I can clone git repo, etc.
SSH keys seem to be working perfectly except through the app.

Let me know if you have any pointers

Thanks

**Comment by mathieugagne** [comment]
Solved my own problem by starting ssh-agent before deploying.

```
deploy:
  override:
    - eval "$(ssh-agent -s)" && ssh-add && bundle exec cap $ENVIRONMENT deploy
```

Won't work if it's not inline. Each step has a different pid. So now the question is why do we not persist the context from one step to another? And why would it not use my already-available ssh-agent?

**Comment by gmalette** [comment]
@dwradcliffe would you know? I think we use(d?) the `SSH_AUTH_SOCK` envar or something

**Comment by dwradcliffe** [comment]
Yeah, but I've also used it without. Are you sure that the user running the background job (we use a `shipit` user) has the key that has access?

**Comment by mathieugagne** [comment]
Yeah I'm pretty sure. I don't think running the ssh-agent and adding the default key would work as a workaround otherwise.
I ran the task adding a `whoami` step and made sure that it was the same user. I believe all is fine on that side.

**Comment by byroot** [comment]
I'd have a couple questions:

  - Which version of capistrano are you using?
  - If it's capistrano 2: Do you use the gateway feature?

This stackoverflow thread might contain the solution to your problem: http://stackoverflow.com/questions/3269578/capistrano-asks-for-password-when-deploying-despite-ssh-keys

**Comment by mathieugagne** [comment]
- Which version of capistrano are you using?
    - We use both versions, depending on the project. The problem occurs on both versions.
- If it's capistrano 2: Do you use the gateway feature?
    - I do have `forward_agent` everywhere. It won't connect to git otherwise. We usually don't setup ssh keys on our servers and simply forward our own to the ssh connection on deployment.

That being said, the error doesn't occur when it updates the deploy folder at the specified commit. It is only on the `bundle exec cap $ENVIRONMENT deploy`. All previous git queries are executed without any issues, using the ssh key on the box to connect to github. Remove the ssh key and git queries fail. So it is for the duration of the deploy step only that it somehow doesn't recognize the ssh context it's in. Hence I have to start the agent and add the key to get it working.

Appreciate your help guys. This is likely out of scope for this repo. Sounds more like a sysadmin issue on my shipit box than a software-related one. I'm ok leaving it as is until somebody else starts having the same issue as me.

**Comment by byroot** [comment]
> This is likely out of scope for this repo. Sounds more like a sysadmin issue on my shipit box than a software-related one.

It definitely is. But from experience, capistrano asking for password when it shouldn't is a relatively common issue. So if we can figure it out, it would be great to have the resolution posted here :)

**Comment by mathieugagne** [comment]
What's curious about it is that it works for `git` but not for `bundle`. Is there a difference between both actions from an implementation point of view in Shipit?

**Comment by byroot** [comment]
> git but not for bundle

`bundle`? you mean `cap`? 

> Is there a difference between both actions from an implementation point of view in Shipit?

No Shipit simply shell out using the same primitive for boths.

Could you try to put the capistrano SSH in verbose mode to see what is happening? I believe its' `ssh_options[:verbose] = :debug`

**Comment by mathieugagne** [comment]
> bundle? you mean cap?

`bundle exec cap` same same :wink:

**Comment by byroot** [comment]
Yes but in the end it's cap that calls SSH. For a second it though your issue was during `bundle install` for checking out git gems.

**Comment by mathieugagne** [comment]
Agreed. I revised in my update.

I'll run it with verbose and see what happens.

**Comment by byroot** [comment]
Closing assuming it's solved by now.
