### ISSUE TITLE
Shipit doesn't handle very long commit message very well

### ISSUE THREAD

**Issue by mlhamel** [Shopify/shipit-engine#473]
It broke the css when pushing basically a revert of revert of revert...

Example use case:

![pasted_image_at_2015_08_20_01_17_pm](https://cloud.githubusercontent.com/assets/44640/9390623/30a32188-4740-11e5-96c2-0e8c130ceb4f.png)

**Comment by byroot** [comment]
I think we should simply truncate at 79 characters like GitHub does.

We could also parse Reverts like we parse pull request messages.

**Comment by mlhamel** [comment]
First solution is probably enough, truncating would be great.

**Comment by byroot** [comment]
Fixed in https://github.com/Shopify/shipit-engine/commit/8d9d1bd9df729f9573560f4292120a36d1516ada
