### ISSUE TITLE
Troubleshooting 'create deploy' step

### ISSUE THREAD

**Issue by everestx** [Shopify/shipit-engine#475]
Hi there, I've been going through the README and I have the ShipIt UI and sidekiq working.  Meaning, I have created a stack, the sidekiq is running and it's syncing with Github.  I don't have any tracebacks in either the sidekiq or the rails log. However, when I create a deploy I get no output from the web ui and the deploy remains in pending status.

I don't see any processes generated from the deploy.  I've even used a simple deploy override in `shipit.yml` to print out the environment.  Can you recommend some troubleshooting steps to see why the deploy doesn't actually trigger or even move past the 'pending' status?

Also, as an aside. Is there a way to force 'abort' a pending deploy.

My example shipit.yml
```
---
deploy:
  override:
    - 'whoami && env'
```

**Comment by byroot** [comment]
> Can you recommend some troubleshooting steps to see why the deploy doesn't actually trigger or even move past the 'pending' status?

Hum, right. I would say you can first try to execute the deploy from Rails console:

```ruby
>> Deploy.last.update_column(:status, 'pending')
>> PerformTaskJob.new.perform(Deploy.last)
```

That might uncover some issue. If you figure it out or are stuck please let me know. (Also I assume you have at least basic Rails knowledge).

> Also, as an aside. Is there a way to force 'abort' a pending deploy.

During a deploy, you have a button to send a `SIGTEM`. If by force abort you mean SIGKILL, then no, at least not yet, but I would accept a PR with that.

**Comment by everestx** [comment]
Thanks for the response.  I do have some Rails knowledge, so this is very helpful.  That said, running the deploy from the Rails console runs the deploy successfully.  Then browsing to the deploy page via the webui shows all the console output.  There's just something that doesn't trigger the deploy to run, which I'll have to keep digging on.

I don't have a button for `SIGTERM` on the deploy page, but I suspect that is because the page doesn't render fully while it's pending and maybe part of the problem here.

I'll keep digging as I don't have much more feedback at the moment.

**Comment by byroot** [comment]
Hum, then it must be that sidekiq either don't receive the job, or drop it.

Are you sure both shipit and sidekiq point to the same Redis db / host?

**Comment by byroot** [comment]
>  I have the [...] sidekiq working

Sorry I just noticed now. When you say sidekiq working, you mean you started the Sidekiq process in your terminal with `bundle exec sidekiq`?

**Comment by everestx** [comment]
Yes, `bundle exec sidekiq -c 1` is the command that I used.  Sidekiq will process jobs from the stack settings page when I sync the webhooks, so I assume the rails web app and sidekiq are using the same redis instance.  My other thought was whether they are using the same namespace (prodution/development, etc).  I was going to check into that today.

**Comment by byroot** [comment]
Closing this assuming it's solved.

**Comment by everestx** [comment]
I eventually got back to this issue on my end and got things working.  I started anew with the latest revision as of yesterday (1/28/2016) and things are working as expected.  So yes, this is resolved.
