### ISSUE TITLE
Commit status hook.

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#477]
## Context

Since Shipit aggregates multiple commit statuses, and also knows about locks and ongoing deploys, it's a good candidate to be able to notify people that they have commits ready to be shipped, or blocking shipping.

## Feature description

I think 2 events would make sense:

### Ready to ship

The trigger conditions would be similar to the automated deploy one:
  - All required statuses are successful
  - The stack is not locked
  - The stack is not being deployed 

### Build failure

The trigger condition would be:
  - One of the required statuses went to `error` or `failure`.

## Code pointers:

You can see how automated deploys happen here: https://github.com/Shopify/shipit-engine/blob/82d2aab54ef859bd0c1b69be9c3734fc290241e6/app/models/commit.rb#L128-L133

**Comment by byroot** [comment]
Alternatively, a simpler and more general implementation could be:

## Commit final status:

The trigger condition would be:
  - All required statuses are successful
  - OR one of the required status is `error` or `failure`

If this hook payload includes the stack (meaning the lock status and the deploy status), then the feature described above can easily be implemented by the hook receiver.

**Comment by oliver-fisher** [comment]
Should be fixed with #479  and #486.
