### ISSUE TITLE
Finalize migration to organization hooks

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#495]
We're already using them for monitoring user memberships.

Using them for push and status event would simplify things quite a lot, we wouldn't have to setup new hooks for stacks.

It also open up interesting possibilities, like for example automatically creating stack when a shipit.yml is added.

One important concern here that I still ned to figure out is the migration path for existing installations.

cc @dwradcliffe

**Comment by dwradcliffe** [comment]
For migration, I assume you have a task to create the org hook somewhere, and after it does that it can attempt to remove all hooks on individual repos.

**Comment by dwradcliffe** [comment]
Also cc: @baldowl

**Comment by byroot** [comment]
Update: We can't rely solely on Org hooks because there is no "User hooks". So repo hooks are the only way to track repositories owned by regular users.

Org hooks if available should be preferred though, simply because it's less state to track on GitHub side.

**Comment by dwradcliffe** [comment]
:+1:
