### ISSUE TITLE
Deploy button out of the screen

### ISSUE THREAD

**Issue by arthurnn** [Shopify/shipit-engine#510]
see screenshot 
![screenshot 2015-12-08 14 21 58](https://cloud.githubusercontent.com/assets/833383/11666290/c9775918-9db9-11e5-8f34-113975079540.png)

see the third one almost pushed the button to far away. but the first commit, was way to big to fit, and I cannot see the button anymore. 

cc @dwradcliffe 

Using latest version, 0.4.9

**Comment by davidcornu** [comment]
Interesting. This should be truncated as per https://github.com/Shopify/shipit-engine/blob/45d0225276715b6352159b043c3bb4aa07845c2a/app/helpers/stacks_helper.rb#L39.

**Comment by byroot** [comment]
Yes rubygems.org still use a pre-release version of shipit. This was fixed months ago in https://github.com/Shopify/shipit-engine/commit/8d9d1bd9df729f9573560f4292120a36d1516ada

**Comment by arthurnn** [comment]
@byroot what do you mean? I just updated to latest version https://github.com/rubygems/shipit/commit/0bda112d82ec054f0629d645c3d0f9c65051fe43

**Comment by byroot** [comment]
Oh really? WTF!?

**Comment by byroot** [comment]
I just setup that stack and it works for me:
![capture d ecran 2015-12-08 a 16 01 14](https://cloud.githubusercontent.com/assets/44640/11668395/f8a210a6-9dc4-11e5-99d8-97592d87373c.png)

This page is quite heavilly cached with ETags, and the version of the app is not included in the etag.

Try clearing your cache. I think that will fix it. So the real bug to fix is to embed shipit version in those etags.

**Comment by arthurnn** [comment]
I think it is a deploy problem we have. I opened up that in incognito mode, and still has the problem

thanks bro.
