### ISSUE TITLE
After creating new deploy, redirected back to root url

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/shipit-engine#512]
After I create a new deploy, I'm redirected back to the root url, with lots of query params. The deploy is still happening properly in the background, I just need to navigate to find it again.

Example: `/?action=show&controller=deploys&id=381&stack_id=rubygems%2Fshipit%2Fproduction`

**Comment by byroot** [comment]
Hum, weird. That's very similar to https://github.com/Shopify/shipit-engine/pull/505.

I'll try to figure that out.

cc @rafaelfranca

**Comment by byroot** [comment]
SO I confirm I can repro locally, and that it is like #505 due to Rails 4.2.5. Until we figure out the root cause you can lock Rails at 4.2.4 as a workaround.

**Comment by byroot** [comment]
Fixed by #513
