### ISSUE TITLE
Double deploys when auto deploying with Starscream

### ISSUE THREAD

**Issue by angelini** [Shopify/shipit-engine#526]
On February 12th we first noticed a case where Shipit would double deploy (two deploys running simultaneously) every once in a while.

We ran into that case again today with:
https://shipit.shopify.io/shopify/starscream/production/deploys/46566  # Success
https://shipit.shopify.io/shopify/starscream/production/deploys/46567  # Failure (folder already exists)

Starscream is setup to auto deploy when CI passes.

Potentially related, we have two separate Starscream deploys and this has caused bugs with Shipit in the past:
https://shipit.shopify.io/shopify/starscream/production/
https://shipit.shopify.io/shopify/starscream/streams/

"Streams" does not auto deploy.

@byroot @kmtaylor-github

**Comment by kmtaylor-github** [comment]
Seems to be happening more frequently?
https://shipit.shopify.io/shopify/starscream/production/deploys/46583 + https://shipit.shopify.io/shopify/starscream/production/deploys/46584

**Comment by byroot** [comment]
Friendly reminder that this is a public repo ;)
