### ISSUE TITLE
Investigate Airbrush compatibility

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#529]
Discovered with @teu 

A capistrano recipe using https://github.com/mattbrictson/airbrussh was entirely stuck when invoked from shipit.

**Comment by PatKoperwas** [comment]
Hey randomly came across this issue - I had something similar happen when attempting to spawn a Capistrano process from `PTY`. It ended up being a weird issue caused on [this line in Airbrussh](https://github.com/mattbrictson/airbrussh/blob/449f621835600fc93916a52be93db139aa30b3fd/lib/airbrussh/console.rb#L26). The `console_width` ends up being `0` so it never outputs anythings. 

Solved by changing the Airbrussh config to 

```ruby
Airbrussh.configure do |config|
  config.truncate = false
end
```

**Comment by byroot** [comment]
Wow, thanks a lot for the tip!

**Comment by byroot** [comment]
Fix was submitted to Airbrush, no reason to keep this open.
