### ISSUE TITLE
healthcheck url

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#535]
Hi,

when running shipit inside an AWS EC2 instance we face a redirection problem.
An elastic load balancer requires a 200 response in order to deem the instance viable to route traffic to it, however shipit always returns 302 as it redirects an non-authenticated user to github's OAuth gateway. 

I suggest adding in an DMZ healthcheck url (e.g. /status) returning a simple OK http code.

**Comment by dwradcliffe** [comment]
There is `/status/version` which should work.

**Comment by byroot** [comment]
Yes as David said. Also since Shipit is an engine embeded in a host application, you can add any endpoint you'd like.
