### ISSUE TITLE
shipit does not allow to deploy similar stacks

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#537]
Hi,

As we have to test prior to deploying on production, we obviously use git branches. Now I am trying to create a second stack, similar to the one I possess but just the branch changes.

Not really getting an error, just page reloading and nothing is happening. Looked at console but still nothing. 

There should be a way to create unique stacks based on app+branch+env, as deleting a stack effectively removes all history of deployments.

Adding that with custom authentication to web hooks re-adding stacks is super-annoying as we have to update hooks manually every time.

**Comment by byroot** [comment]
I'm not sure i understand the issue. The rpo and env are the same but the branch is different?

**Comment by teu** [comment]
Yes.

**Comment by byroot** [comment]
That would go against tons of assumptions in the code base, starting with the URL routes.

Another feature to allow this is on the wishlist since a while: https://github.com/Shopify/shipit-engine/issues/181

But I'll be honest we have no plans to implement it anytime soon.

**Comment by teu** [comment]
Fair enough, this is not a show-stopper just makes it very annoying to work with the tool as it doesn't go with the well established strategy to branch changes and test before merges.
