### ISSUE TITLE
github hooks don't correspond to stacks

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#542]
Hi,

the difficulty is when having multiple apps/stacks it can be cumbersome to manage github hooks as the urls don't show which stack they mean:

```
https://shipit.host/stacks/2/webhooks/push 
```

While the stack urls in shipit use the app and env names.

**Comment by byroot** [comment]
I just added https://github.com/Shopify/shipit-engine/commit/c04168909ea523896e9dd4bd5097a4cea08ea9ac

You can now lookup stacks by `id`, e.g: `https://shipit.example.com/stacks/42` will redirect you to `/owner/repo/env`. Hope it helps.
