### ISSUE TITLE
Ability to preserve the deployment directory

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#548]
When an error occurs in the deployment, currently there does not seem to be a way to preserve the directory of the deployment for debugging. Would be good to have some shipit.yml value with a default to cleanup but ability to leave it.

**Comment by byroot** [comment]
I wished that feature existed too a couple times. Done in https://github.com/Shopify/shipit-engine/commit/586e0d9dcec29f3642fd97343e76fdc54ead6454

**Comment by teu** [comment]
Brilliant:)
