### ISSUE TITLE
Automatic membership sync for github_teams

### ISSUE THREAD

**Issue by lucasmazza** [Shopify/shipit-engine#553]
On my first install of shipit I added the `github_oauth.teams` config and got locked out of the app, even though my GitHub user is a member of the configured team. 

I found the [`team.rake`](https://github.com/Shopify/shipit-engine/blob/037a280d11b40c5ae7efbb41e69bda4305285b1b/lib/tasks/team.rake#L5-L8) task when greping through the source code, and although there isn't any mentions to it in the docs it sounded like something I needed, but the task is broken due a missing `Shipit` module prefix on the `Team.find_or_create_by_handle` call.

1 - The task is the go-to way for deployments that use the `teams` config? If so, would be nice to have it mentioned in the setup docs and maybe change it work on top of all `Shipit.github_teams` rather than passing the `HANDLE` environment variable.

**Comment by byroot** [comment]
> I found the team.rake task when greping through the source code, and although there isn't any mentions to it in the docs it sounded like something I needed

Indeed the rake task is for the initial import of the team members. I'll fix the documentation thanks for the heads up.

> the task is broken due a missing Shipit module prefix on the Team.find_or_create_by_handle call.

Just pushed a `0.8.2` with that fix, that for the heads up again.


> The task is the go-to way for deployments that use the teams config?

It's only for the initial import or if you can't setup an organization hook. After that the members list is kept updated via hooks. But yes you are right it could definitely be improved.
