### ISSUE TITLE
shipit meltdown

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#562]
Hi,

we experienced a total shipit meltdown today, for no apparent reason (servers runs only shipit) it stopped deploying anything.

One of our deployments is hanging in a constant state of running, when we tried to abort, we are getting:
```
Abort: failed, PID unknown
```

Tried:
- restarting sidekiq
- flushing redis
- restarting passenger app (runs apache/passenger)
- restarting apache

Another stack hangs completely on a commit saying "pending", none of the above also helped. Tried to manually refresh statuses, also no change.

Aside removing the stacks and redoing them, is there any procedure you could provide for such occasions?

Thanks

**Comment by byroot** [comment]
What likely happened here is that sidekiq died without marking those deploys as completed, so now Shipit won't trigger any other deploy because it thinks there is one on the way.

It happened to us once where I had to `docker kill` a background job. It so rare that I never added anything in the UI to fix that state, but we likely should.

In the meantime what you can do to fix the state:

```
$ bundle exec rails console production
> Shipit::Task.active.where('created_at < ?', 1.hour.ago).each(&:error!)
```

**Comment by teu** [comment]
Hi byroot,

excellent, thanks. That seems to have helped with the running one, but not with the pending commit, is that another type of background job?

**Comment by byroot** [comment]
Oh sorry I missed the part about the pending commit. For that there is 2 possiblities:

  - Either that commit is still marked as `pending` on the GitHub side. You can check this via their API: https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref
  - If it's not pending on GitHub, then Shipit must fail to fetch the new status, in that case check the sidekiq UI for failed jobs (`RefreshStatusJob` / `GitHubSyncJob`).

**Comment by teu** [comment]
Might sounds silly, but what sidekiq UI ?

**Comment by teu** [comment]
Actually it helped, the second problem was also a deployment job, however wasn't an hour old when I first ran the job. Great support as always! Thanks @byroot
