### ISSUE TITLE
Digitalocean 

### ISSUE THREAD

**Issue by ahmgeek** [Shopify/shipit-engine#571]
I know this place is for bugs, but I can't post that anywhere else.
I was considering using ship it, but never have a clear Idea about using it with digitalocean.
any hints about that ?

**Comment by byroot** [comment]
You mean installing it on DigitalOcean? If so shipit is just Rails app, you can deploy it pretty much anywhere granted you know the Rails stack.

**Comment by ahmgeek** [comment]
no I mean using it to deploy to DigitalOcean it's either I can't grasp the essence of shipit or I am an ass hole to scrap the README fast.
basically I need to use it instead of capistrano.
so do I need to make a git server on my DigitalOcean and set up ship-it to use it ?
that's all missed from the read me I guess. or again, I've just had some misunderstanding of the tool usage.

also, great work folks <3

**Comment by byroot** [comment]
I'm not familiar enough with DigitalOcean, I though it was regular servers with SSH etc.

But whatever, shipit isn't coupled to capistrano or anything else. If you can deploy your app with a scrupt then Shipit is compatible

**Comment by ahmgeek** [comment]
thanks buddy.
