### ISSUE TITLE
Dealing with passwords / secrets?

### ISSUE THREAD

**Issue by arjun810** [Shopify/shipit-engine#580]
Sorry if this is the wrong place for a question.

Do you have any suggestions for how and where to store secrets, such as database credentials, when deploying with shipit?

The deploy server obviously will need access to these, but I'm not sure of the best way to handle this.

Thank you!

**Comment by byroot** [comment]
>  how and where to store secrets [...] when deploying with shipit?

You have 2 options:
  
  - You can store the secrets on the Shipit server, either somewhere on disk or in the the environment.
  - You can store the secrets **encrypted** inside your repository, and decrypt them on deploy.

We usually do the second using [ejson](https://github.com/shopify/ejson), as you can see here for example: https://github.com/Shopify/js-buy-sdk/blob/602b05cec35eace50481762f731ada58aba4da46/shipit.yml#L4

**Comment by casperisfine** [comment]
I'll assume this is solved. Feel free to re-open if you have further questions.
