### ISSUE TITLE
Deployment without SPoF

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#588]
Hi,

any thoughts on deploying shipit on multiple machines? As shipit is not stateless, what would be necessary to ensure that we could run shipit on multiple boxes via load balancer?

Thanks

**Comment by byroot** [comment]
You shouldn't have any problem running Shipit on two hosts at the same time. If you do, please report it I'll fix the issue.

> As shipit is not stateless

It actually is.

**Comment by teu** [comment]
Excellent news. Thanks @byroot !
