### ISSUE TITLE
Docs: Setting up Application in Github

### ISSUE THREAD

**Issue by alexcameron89** [Shopify/shipit-engine#594]
I'm having issues setting up my application, specifically the callback URL in GitHub. Is there a specific URL that I should set it to? I'll be happy to send a PR with basic instructions on GitHub App setup for people who haven't set one up before.

### Github Settings
**Homepage URL**: [http://ak-shipit.herokuapp.com/](http://ak-shipit.herokuapp.com/)
**Authorization callback URL**: [http://ak-shipit.herokuapp.com/](http://ak-shipit.herokuapp.com/)
**Hosting**: Heroku
**Error happened after**: `Started GET "/github/auth/github/callback?code=42df00e4df49d6c52b43&origin=http%3A%2F%2Fak-shipit.herokuapp.com%2F&state=6813555bb5fcfcf6dec88daed05b7a3b013dfade53e46c2d"`

**Comment by byroot** [comment]
Good point, the doc isn't very clear. It should be https://yourdomain/github/auth/github/callback

**Comment by alexcameron89** [comment]
Thanks! That worked.
