### ISSUE TITLE
Continuous deployment is not working as expected

### ISSUE THREAD

**Issue by arbaaz** [Shopify/shipit-engine#607]
If I merge something to master, I expect shipit to deploy it but the deployment is not proper. 

I think, it is using git cache.

I have to manually clear git cache from settings and redeploy.

**Comment by byroot** [comment]
Could you be more specific? What makes the deployment not proper?

**Comment by arbaaz** [comment]
For heroku deployment,

I had `git push heroku master` in `deploy.overide` which was not deploying the app on heroku.

I changed it to `git push heroku +HEAD:master`. It started working as expected.

**Comment by arbaaz** [comment]
@byroot Thank you for the quick reply. Appreciate it.

**Comment by dwradcliffe** [comment]
@arbaaz To deploy to heroku, there's a nice shortcut that works well for us:

```yaml
deploy:
  override:
    - push-to-heroku heroku-app-name
```

**Comment by arbaaz** [comment]
@dwradcliffe Thanks man!

**Comment by arbaaz** [comment]
@dwradcliffe: How would you deal with this?
```
push-to-heroku heroku-app-name
pid: 2713
Current heroku release: v14
Pushing to heroku.
The authenticity of host 'heroku.com (xx.xx.xx.xx)' can't be established.
RSA key fingerprint is xx.xx.
Are you sure you want to continue connecting (yes/no)? 
```
