### ISSUE TITLE
Reveal Shipit's authentication to outside of the engine

### ISSUE THREAD

**Issue by bspellio** [Shopify/shipit-engine#610]
The use case:

I'm currently working on an application which includes both the Shipit engine and other endpoints/functionality not related to Shipit. Users of this "other functionality" should still be authenticated and it would be convenient to use the authentication system has already built into Shipit.

An example `routes.rb` with a proposed interface, inspired by devise:

```ruby
Rails.application.routes.draw do
  mount Shipit::Engine, at: '/'

  Shipit.authenticate do
    resource :some_model
  end
end
```

This API also allows for use with other engines as well as eliminating the need for all controllers to inherit from `Shipit::ShipitController` to gain access to the authentication.

I understand this use case is a bit niche, but I am curious about what the interest level is on a feature like this. This is definitely something I would be prepared to build out in a fork if it we like the idea.

**Comment by byroot** [comment]
I wouldn't be opposed to such feature. But I have to admit I'm not sure how I'd go about implementing it.

But if you say Devise does it I can take a look.

**Comment by byroot** [comment]
Alternatively, would including a module in your controllers be ok?

I understand you don't want to have to inherit from `Shipit::ShipitController`, but if you could just include `Shipit::Authentication` would that work for you?

**Comment by bspellio** [comment]
Hmm I'm not sure I follow, that sounds like a great solution, but I can't seem to find the module `Shipit::Authentication`?

**Comment by byroot** [comment]
It doesn't exist yet, but It could. That's why I'm asking if that would be a satisfactory solution for you?

**Comment by bspellio** [comment]
Ah okay I see, then yes, this seems like a great solution.

**Comment by casperisfine** [comment]
Done. Let me know if you have any issue with it.
