### ISSUE TITLE
Reveal a stack's commits in the api

### ISSUE THREAD

**Issue by bspellio** [Shopify/shipit-engine#611]
Is there a reason the endpoint `/api/stacks/<stack_id>/commits` doesn't exist?

It would be awesome to have an index of commits and to be able to do basic filtering on them i.e. deployed vs. not deployed.

Thoughts on this? Definitely would be up to put together a PR for this if there's some interest.

**Comment by byroot** [comment]
A PR would be welcome.

**Comment by casperisfine** [comment]
I implemented a very basic version of that endpoint. Feel free to submit PRs if you want it to have more features.

**Comment by bspellio** [comment]
Wow that's great! Thank you.
