### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by sgringwe** [Shopify/shipit-engine#615]
Is there any plans to add a Changelog? There are a lot of great improvements going into this project, but it can be hard to follow what they are.

**Comment by casperisfine** [comment]
That would be good indeed. I'll consider it but no promises.

**Comment by casperisfine** [comment]
Ok, I started a CHANGELOG https://github.com/Shopify/shipit-engine/blob/master/CHANGELOG.md
