### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by pollosp** [Shopify/shipit-engine#624]
Setting up the github oauth callback we had a problem, in the example you have in https://github.com/Shopify/shipit-engine/blob/master/config/secrets.development.shopify.yml#L10 you are adding `# Set the "Authorization callback URL as <host>/github/auth/github/callback`. 
But at least from version 0.12.1 https://github.com/Shopify/shipit-engine/blob/master/config/routes.rb#L47  it is `Authorization callback URL as <host>/github/auth/github/callback` it is not urgent, but I trusted the documentation and I waste a little bit of time looking why it doesn't work.
Thanks you.

**Comment by casperisfine** [comment]
Hum, I don't understand, the 2 paths you posted and linked matches.

**Comment by pollosp** [comment]
This `/github/auth/github/callback` didn't match in my shipit deployment only `/github/auth/github` I will check it again maybe i did something wrong, thanks for your quick answer :)

**Comment by casperisfine** [comment]
<img width="475" alt="capture d ecran 2016-12-01 a 12 12 35" src="https://cloud.githubusercontent.com/assets/19192189/20792624/284035cc-b7c3-11e6-973a-199cff68063a.png">

This have been working since ages ^

**Comment by pollosp** [comment]
Weird this is my experience:

![shipit](https://cloud.githubusercontent.com/assets/1783343/20792781/0024bdf0-b7c4-11e6-936d-cc5f1a9afece.gif)

**Comment by casperisfine** [comment]
You can't go directly on `/callback`. It's GitHub that redirect you there at the end of the OAuth flow.

If you look into your browser dev tools. you'll see that when you go to `/github/auth/github` you are then redirected to `github.com`, then `/github/auth/github/callback` and finally to `/`.

See: https://developer.github.com/v3/oauth/

**Comment by pollosp** [comment]
👍
