### ISSUE TITLE
npm/yarn publish support

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/shipit-engine#625]
The UI Dev Acceleration team would like to automate publication of our npm packages.  Stuff we'd like to see:

* Automatically publish to npm repositories when a package is version bumped
* Run prepublish scripts
* Distinguish between private/public packages and publish to the relevant registry

Things devs still have to handle:
* Version bumps
* Version tagging

Out of scope:
* Monorepos (i.e., we'll break down the many packages in `shopify/javascript` into separate repos)

/cc @byroot - our team has the bandwidth to implement this feature, but I'll need a little help getting my local environment running
/cc @lemonmade

**Comment by casperisfine** [comment]
So according to https://docs.npmjs.com/getting-started/publishing-npm-packages besides calling `npm publish` you need:

  - Credentials, via `npm adduser` / `npm login`, this is up to the installation of shipit to have this available.

 No in term of Shipit-engine:

  - > Run prepublish scripts

     Shouldn't be a problem, as long as there is some kind of convention for this.
  - > Distinguish between private/public packages and publish to the relevant registry

     Is there a way to detect this?

**Comment by GoodForOneFare** [comment]
@casperisfine scripts are just bash scripts stored a package's `package.json` file (e.g., [a prepublish hook](https://github.com/Shopify/decaf/blob/master/package.json#L21))  You can run them via `npm run script_name`.

Public/private is also defined in `package.json`.  A private package [is flagged by adding`"private": true`, and providing a `publishConfig`](https://docs.npmjs.com/files/package.json#private).

**Comment by casperisfine** [comment]
Ok, so assuming you have credentials available on the Shipit machine, then all it takes to publish npm packages is:

```
deploy:
  override:
    - npm run <script_name>
    - npm publish
```

We can eventually make Shipit detect that a repo is a npm package, and automatically run `npm publish`, in the end it would be:

```
deploy:
  pre:
    - npm run <script_name>
```

**Comment by GoodForOneFare** [comment]
After discussion, the UI Dev Acceleration team will focus on splitting up its monorepo, and adding `shipit.yml` files to each JS package.  With those in place, anyone will be able to deploy our JS stacks via shipit.

Autopublishing on version bumps is still wanted, but it can wait until the above groundwork is complete.

**Comment by GoodForOneFare** [comment]
Initial support added in https://github.com/Shopify/shipit-engine/pull/631.
