### ISSUE TITLE
What is the correct way to access API Tokens?

### ISSUE THREAD

**Issue by bspellio** [Shopify/shipit-engine#629]
I'm currently writing a CLI to interact the Shipit's API and I am curious what the intended way to access/generate API tokens is?

My current solution was to manually generate one in the rails console, but this feels a bit hackish. Is there another way, I was unable to find one by looking at the application code.

**Comment by casperisfine** [comment]
It's definitely hackish. I'd like to have a UI to do it, but it's not done yet, and there isn't anyone working on it really.

I'm afraid Rails console is the current official way to generate an API client :/

**Comment by bspellio** [comment]
I'd be open to opening a basic PR to get the ball rolling.

Perhaps a simple form on the stack show/settings page where it allows you to generate tokens and specify the user/rights?

**Comment by casperisfine** [comment]
One of the big blockers for this is user permissions. 

Once the API Client is created, who should be able to see the API Token?

I guess a simple pre version could show it only to the user that created it.

Also note that ApiClients can be scoped to a single stack, but also global.

**Comment by dwradcliffe** [comment]
Or only show the token immediately after generating it.

**Comment by casperisfine** [comment]
That would totally works yes. Sounds good to me. @bspellio feel totally free to works on this. A PR would be absolutely welcome.

**Comment by casperisfine** [comment]
Even if it only handles scoped or global api clients.

**Comment by bspellio** [comment]
I'll take a look sometime this weekend.

**Comment by bspellio** [comment]
Just to follow up, how do you go about local development of Shipit at Shopify? Do you have a dummy OAuth application? I see that there's a dummy application in the `test` directory, but it's unclear if that's intended for local development.

Thank you for any insight you can provide!

**Comment by byroot** [comment]
> Do you have a dummy OAuth application?

We just create a personal OAuth application for local dev. Just like for prod. We also use a personal token.

> I see that there's a dummy application in the test directory, but it's unclear if that's intended for local development.

Yes you can use it for local development, see the `dev.yml`: https://github.com/Shopify/shipit-engine/blob/6be5e48aa1981d4947ef02e08be4363e92c3f09c/dev.yml#L15-L19

(dev is an internal tool, but you can still use the commands as is to get `rails s` or `rails c`).
