### ISSUE TITLE
Auto merge queue got stuck after it was lock for some time

### ISSUE THREAD

**Issue by rafaelfranca** [Shopify/shipit-engine#665]
When we had a lock for more than 30 minutes the auto merge queue stoped to work. I had to clean all the PRs and add back to it be able to work again.

**Comment by casperisfine** [comment]
Unfortunately I'm afraid I don't have enough information to know what might have happened.

There is several reasons why Shipit might not merge a PR after the lock is removed:
  - Master is failing.
  - Master is backlogged (too many undeployed commits).
  - Your PR stayed too long in the queue, and need to be reconfirmed.

However based on the chat logs, none of those reasons seem likely. Hopefully this issue will manifest itself again at a time where I can investigate it.

**Comment by rafaelfranca** [comment]
👍. One thing that I noticed is that there was some PRs in the queue before mine and when the person tried to reconfirm something exploded. @TempestMia may have some information about that case.

**Comment by casperisfine** [comment]
> when the person tried to reconfirm something exploded.

That was a bug in our chat bot, but was localized to it. The actual API request to Shipit to confirm was successful.

**Comment by casperisfine** [comment]
I believe I identified the problem. 

Step to reproduce:
  - Lock the stack
  - Add a few PRs to the queue
  - Manually merge the first one in the queue
  - Unlock the stack
