### ISSUE TITLE
Rollback could be less confusing

### ISSUE THREAD

**Issue by tjoyal** [Shopify/shipit-engine#670]
In moment of crisis, sometimes there is a need to rollback some code.

<img width="1134" alt="main" src="https://cloud.githubusercontent.com/assets/207902/23633264/fb90a3e6-02bc-11e7-8211-ac1f415bfa13.png">

When hitting rollback to this deploy, the user is redirected to the rollback confirmation page that contain what I find confusing information:

<img width="1117" alt="rollback-confirmation" src="https://cloud.githubusercontent.com/assets/207902/23633282/0de72e7a-02bd-11e7-89dc-d7b8f877cd26.png">

I rarely use the rollback mechanism, and when I last did I was really puzzled by the page. I was not sure anymore if I was in the process of re-deploying the faulty code as it says that these same commits will be included in the operation I was trying to perform.

Maybe it's me, but should Shipit avoid mentioning "rollback" at all? It's more of a "deploy an earlier commit" to me.

If we find commits being removed from master to be relevant, they could be referenced in some other way (eg.: These commits will be removed from the servers). I would also like to see what will be the commit sha that will be deployed?

Thoughts?

**Comment by casperisfine** [comment]
What about replacing `Commits included in the rollback` by `Commits that will be rolled back`?

**Comment by tjoyal** [comment]
I would be ok with it. Seems like something that will remove most of the confusion with minimal effort.

I think there is also value to add info as to "the target" where we are rolling back, but just the current caption change would be a great start.

**Comment by casperisfine** [comment]
the target?

**Comment by tjoyal** [comment]
target: "rollback to this deploy"

**Comment by casperisfine** [comment]
This "target" as you call it have been subject to a lot of bikeshedding over the years, and this is what everybody settled on. I really don't want to trigger that bikeshedding again as I almost rage quit from it.

**Comment by tjoyal** [comment]
Alright, no problem. I'm more than happy to settle on your proposition if it is all right?

> What about replacing "Commits included in the rollback" by "Commits that will be rolled back"

I'm I crazy to find it confusing in the fist place? I'll be happy to keep it as-is if I'm the only one.

**Comment by casperisfine** [comment]
It's perfectly understandable IMO, but I'm no UX expert. 

In any case, feel free to submit a PR to close this issue.
