### ISSUE TITLE
Preventing duplicate deploys

### ISSUE THREAD

**Issue by sgringwe** [Shopify/shipit-engine#685]
Is there anything to prevent duplicate deploys? I know I've seen warning messages in the UI if about to do so, but is there anything to actually prevent the same stack being deployed at the same time?

Sorry if I missed it! Couldn't find anything in the docs or in some basic code search.

**Comment by byroot** [comment]
Yes. If you attempt to deploy while there is an active deploy on the way, you'll be taken back to the deploy page and asked to acknowledge you want to deploy concurrently (hint most likely you won't).

Line of code wise it's this: https://github.com/Shopify/shipit-engine/blob/1217e7d04b686ec0f2d7b354b83cbfd0e4ad8757/app/controllers/shipit/deploys_controller.rb#L23

Technically, a race condition is possible, but the window is small enough that it's unlikely.
