### ISSUE TITLE
rake teams:fetch doesn't remove users

### ISSUE THREAD

**Issue by szemek** [Shopify/shipit-engine#688]
Hi,
please correct me if I am wrong but as far as I checked code
https://github.com/Shopify/shipit-engine/blob/master/lib/tasks/teams.rake#L11-L12
https://github.com/Shopify/shipit-engine/blob/master/app/models/shipit/team.rb#L55-L60
and it seems to me that `rake teams:fetch` can only add new users.
I'd like to, in a single rake task, conveniently remove users that are no longer in a team.
What do you think about task under different name `rake teams:synchronize` and deprecating the existing one?
I can work on PR after your response.

**Comment by byroot** [comment]
The code you linked to does remove users that are no longer part of a team. There might be a bug, but at first sight it already does what you are asking.

If you have evidence that it doesn't work, then feel free to PR either a failing test case, or a full fix.

**Comment by szemek** [comment]
Thanks for checking, and sorry for this issue. I should have slept longer today 😪 
You're right, membership of user is removed, when user doesn't belong to team anymore.
Nonetheless records for `Shipit::User` model will stay in database, but for my needs it doesn't matter.

**Comment by byroot** [comment]
> Shipit::User model will stay in database

Yes but it's on purpose. They are likely to be commit or deploy authors, so there is no reason to delete them from the database.
