### ISSUE TITLE
TypeError when I try to deploy using 0.18.0

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/shipit-engine#694]
I just upgraded to 0.18.0 and I'm getting this error when I try to deploy anything:

```
TypeError: no implicit conversion of Symbol into String
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/lib/shipit/command.rb:89:in `spawn'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/lib/shipit/command.rb:89:in `block in start'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/lib/shipit/command.rb:73:in `with_full_path'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/lib/shipit/command.rb:87:in `start'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/jobs/shipit/perform_task_job.rb:76:in `capture!'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/jobs/shipit/perform_task_job.rb:90:in `capture'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/jobs/shipit/perform_task_job.rb:63:in `block in checkout_repository'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/redis-objects-1.2.1/lib/redis/lock.rb:58:in `lock'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/models/shipit/stack.rb:281:in `acquire_git_cache_lock'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/models/shipit/task.rb:120:in `acquire_git_cache_lock'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/jobs/shipit/perform_task_job.rb:62:in `checkout_repository'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/jobs/shipit/perform_task_job.rb:19:in `run'
	/applications/shipit/shared/bundle/ruby/2.3.0/gems/shipit-engine-0.18.0/app/jobs/shipit/perform_task_job.rb:12:in `perform'
```

@byroot

**Comment by casperisfine** [comment]
So this breaks on: `PTY.spawn(@env, *interpolated_arguments, chdir: @chdir)`.

It mean that any of `@env`, `@chdir`, or a member of `interpolated_arguments` is a Symbol.

  - [`@chdir` is casted to string in the constructor no matter what](https://github.com/Shopify/shipit-engine/blob/4b36f5febe357ef05bff6b87a854252c99d94783/lib/shipit/command.rb#L22)
  - [`@env` is basically `Shipit.env`](https://github.com/Shopify/shipit-engine/blob/4b36f5febe357ef05bff6b87a854252c99d94783/lib/shipit/commands.rb#L20-L22) so it could very hardly be anything else than a Hash.
  - `perform_task_job.rb:63:in `block in checkout_repository'` indicate that the command that is executed mostly come from constant values: https://github.com/Shopify/shipit-engine/blob/4b36f5febe357ef05bff6b87a854252c99d94783/lib/shipit/stack_commands.rb#L19-L26

So this is quite puzzling. I pushed a new branch with improved error reporting on this part: https://github.com/Shopify/shipit-engine/tree/dwradcliffe-debug

Would you mind trying it out so we get a more helpful error message?

**Comment by dwradcliffe** [comment]
`got: env={"SHIPIT"=>"1", :HOME=>"/applications/shipit/"}, args="test", "-d", "/applications/shipit/releases/20170507182058/data/stacks/rubygems/rubygems.org/staging/git/.git", chdir="/applications/shipit/releases/20170507182058/data/stacks/rubygems/rubygems.org/staging/deploys"`

I'm guessing the `:HOME` part is the problem.

**Comment by casperisfine** [comment]
Yes, it definitely is. I think Rails 5.1 has symbol as keys for `Rails.application.secrets`. That will be simple enough to fix. Not sure why it wasn't a problem for Shopify's deployment.

**Comment by casperisfine** [comment]
@dwradcliffe I pushed a fix to master, can you try it out. If it works for you I'll release a `0.18.1`.

**Comment by dwradcliffe** [comment]
@casperisfine 👍 it works!

**Comment by casperisfine** [comment]
`0.18.1` released.

**Comment by dwradcliffe** [comment]
@casperisfine Thank you!!
