### ISSUE TITLE
Record deploys performed in emergency mode

### ISSUE THREAD

**Issue by casperisfine** [Shopify/shipit-engine#699]
Feature request by @pallan 

By design Shipit tries to prevent honest mistakes, but leaves as much leeway as possible to users, so they can deal with emergencies. That is why, failing statuses prevent deploying by mistakes, but ultimately it's possible to turn on the emergency mode and deploy a failing build anyway.

However it doesn't mean there is no accountability, as such it's important to have proper traceability.

In that spirit, it would be good to record on the deploys if they were triggered with emergency mode.

As I see it:

  - We add a new `emergency boolean not null default false` column on `tasks`.
  - When the deploy / rollback record is created, we check if it would have been allowed without emergency mode, if not we set `emergency = true`.
  - We add an icon or something in the deploy list for deploys that bypassed the ci statuses.

cc @pallan @wvanbergen @DazWorrall

**Comment by perobertson** [comment]
It would also be nice to have the ability for shipit to notify a slack channel on emergency deploys. That way anyone who wants to say informed can watch that channel.

**Comment by casperisfine** [comment]
> shipit to notify a slack channel 

On that specific note, it was decided not to add any kind of messaging notification to Shipit itself a while ago.

The thing is, there is many different IM services, some people would like mail notifications as well maybe, etc, etc. It kinda feels like pandora's box from a project perspective.

That is why Shipit supports webhooks, and people wanting such feature are expected to use the webhooks infra for it.

And that's actually what we do at Shopify:
![capture d ecran 2017-05-18 a 17 37 09](https://cloud.githubusercontent.com/assets/19192189/26210668/a9910cda-3bf0-11e7-993b-1d6896c30532.png)

**Comment by pallan** [comment]
Another potential piece of value would be a comment(s) the user can add pre- or post-deploy to indicate why they had to perform the emergency

**Comment by orenmazor** [comment]
I really like the bit about having to explain the reason for the emergency :+1:  I'm sure Ulf the time it'll be "Fuuuuuuuu" or "fuck _______ remote tests" but still worth having. 

Re: notifications. I'd be pretty happy even if there was a FORCED_DEPLOY=1 env variable available to scripts.

**Comment by byroot** [comment]
> I'd be pretty happy even if there was a FORCED_DEPLOY=1 env variable available to scripts.

Very good idea.
