### ISSUE TITLE
So this is totally broken now, right?

### ISSUE THREAD

**Issue by kulte** [Shopify/shipit-engine#716]
I get this error basically all the time:

![screen shot 2017-08-22 at 4 03 43 pm](https://user-images.githubusercontent.com/633289/29584988-807e9016-8753-11e7-9081-9887fdccee1d.png)

Is it safe to call this piece of software abandonware? Just don't want to invest any more time in an unmaintained, broken solution.

**Comment by rafaelfranca** [comment]
> Is it safe to call this piece of software abandonware?

It is not. This project is maintained and we use in production every single day hundreds of time. It seems you found a bug in the state_machines gem in your application. What is the content of Gemfile.lock of your application?

**Comment by byroot** [comment]
Make sure `state_machines-activerecord` is at version `0.5.0`, I think the error you got happens if you get `state_machines = 0.5.0` and `state_machines-activerecord < 0.5.0`.

If it's indeed that, we can force it in the gemspec to avoid other people running into this in the future.

**Comment by rafaelfranca** [comment]
Ok. Just for the image you posted I already know what is happening.

You are using the shipit-engine 0.19.0 that is the latest release. While that version has correct code, one of our dependencies `state_machines-activerecord` is locked to the version 0.4.x but its dependency `state_machines` is not locked to the 0.4.x series.

When you installed `shipit-engine` in your application you got `state_machines-activerecord` 0.4.0 but  `state_machines` 0.5.0 which are incompatibles.

While we can fix this problem in the `shitit-engine` side, and [we already did](https://github.com/Shopify/shipit-engine/commit/6d33a7339329f72020a2e7fa52da81e33b5131e4), it is unfortunately a `state_machines` problem.

You have two options to fix this problem temporarily:

1) Force the version of `state_machines` to be 0.4.0 in your Gemfile adding the following code to it.

```ruby
gem 'state_machines', '~> 0.4.0'
```

2) Use the shipit-engine master version that contains the fix adding the following code to your Gemfile.

```ruby
gem 'state_machines', github: 'Shopify/shipit-engine'
```

The permanent fix will only be available when we release the next version of shipit-engine.

Last, but not least, I'd like to bring the attention to the tone of your issue. While I understand that you may be frustrated after a day debugging issues in other people software it is not ok to open an issue like this implying that we are have obligations to you, or any other user of this gem. This software, as the license make it clear is 'PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND'. Even with that we do our best to support every user that opens an issue politely.

Politeness is exactly what is missing in your issue, and while I spent some time to understand your problem and fix it, other people would just ignore your issue closing without any reply or with a reply in the same level of your issue.

There is no indication in this repository that the software is abandonware or unmaintained. The last commit is from one day ago. Even if it was not, this is one of the most well maintained open source projects that I know. If you have spend 5 minutes reading the already closed issues you will see that is the case.

So, for the next issue that you open in an open source project try to be more emphatic with who is in the other side.
