### ISSUE TITLE
Could not find table 'Users'

### ISSUE THREAD

**Issue by alexcurtin** [Shopify/shipit-engine#717]
I have setup shipit with all defaults and ran rake db:create and db:setup and am hitting this active record issue after github auth to localhost:300 any ideas?

def table_structure(table_name)
          structure = exec_query("PRAGMA table_info(#{quote_table_name(table_name)})", "SCHEMA")
          raise(ActiveRecord::StatementInvalid, "Could not find table '#{table_name}'") if structure.empty?
          table_structure_with_collation(table_name, structure)
        end
        alias column_definitions table_structure

**Comment by rafaelfranca** [comment]
Have you run `rake shipit:install:migrations` before `rake db:setup`?

**Comment by alexcurtin** [comment]
Thanks @rafaelfranca now I cannot get the migrations to pass, tried both sqlite3 and postgres.

hipit master ✗ rake db:migrate                                                                            ⎈  minikube ☁  continuous-integration-172919
Running via Spring preloader in process 68374
== 20170823165768 ConvertStiColumns: migrating ================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

compared with non class/module/Users/acurtin/.rvm/gems/ruby-2.3.4/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `<='
/Users/acurtin/.rvm/gems/ruby-2.3.4/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `block in matches?'
/Users/acurtin/.rvm/gems/ruby-2.3.4/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `any?'
/Users/acurtin/.rvm/gems/ruby-2.3.4/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `matches?'
/Users/acurtin/.rvm/gems/ruby-2.3.4/gems/state_machines-0.5.0/lib/state_machines/integrations.rb:76:in `block in match'

**Comment by rafaelfranca** [comment]
See https://github.com/Shopify/shipit-engine/issues/716#issuecomment-324171709

**Comment by alexcurtin** [comment]
@rafaelfranca Awesome man thanks. Its up and running now. Do you guys have a video tutorial or walk through in addition to the docs on this repo? That would be super useful to have a /demo folder or tutorial video. I'll try to follow the docs closely.

**Comment by rafaelfranca** [comment]
Glad it is working! We don't have any video tutorial or demo app, right now the docs on this repo is the only source of documentation.

I'm closing this issue now since it seems solved, but feel free to open new issues if you find something broken.

Thank you for using this project ❤️
