### ISSUE TITLE
Allow PRs to be added to the merge queue when they still have pending statuses

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/shipit-engine#719]
Right now, you are not allowed to add PRs when some of the required CI statuses are still pending (or missing). We should make it possible to add a PR to the merge queue, but wait with merging until all required CI statuses are green.

- Other PRs should be able to be merged while the PR is still waiting for a green status, even if they are enqueued later than the PR in question.
- We should start the timeout counter as soon as the PR is enqueued, and not once the CI statuses are green, to make sure we ping the submitter if it takes longer than 20 minutes.

Failure handling:
- When a PRgets a red status, we remove the PR from the queue, and tell the user.
- When a PR doesn't get all the green statuses in X minutes, we remove the PR from the queue.

@Shopify/pipeline does this make sense?

**Comment by casperisfine** [comment]
Shouldn't be too hard to implement.

I indeed got questions from people confused by their PR being ejected from the queue because statuses were pending.

If people actually want it, we can do it.
