### ISSUE TITLE
Allow specifying a maximum age for branches to be allowed to be added to the merge queue

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/shipit-engine#720]
This would prevent master failures when old, outdated branches get merged, and push people to rebase instead. This should be based on the merge base of the PR.

@Shopify/pipeline thoughts?

**Comment by kirs** [comment]
I think this would be pretty great. I remember experiencing this myself and merging an old branch that failed on master.

**Comment by bspellio** [comment]
This is a great idea. Just to clarify, this would still be "overridable" via emergency mode, correct?

**Comment by wvanbergen** [comment]
Yes. Emergency mode only impacts deploying PRs on master, not the merge queue functionality. 

Having said that, we may need an emergency mode for the merge queue as well eventually. For now, people can just merge their PRs by hand rather than using the merge queue.
