### ISSUE TITLE
Merge queue: merge order is LIFO instead of FIFO

### ISSUE THREAD

**Issue by bdewater** [Shopify/shipit-engine#736]
For a queue I was expecting pull requests to be merged in the order their merge was requested. This doesn't seem to happen.

IMO this is also a desirable property to have because eventually the `revalidate_after` logic will kick in if a PR keeps getting pushed back in line.

**Comment by casperisfine** [comment]
It's supposed to be FIFO. If it's not, it's bug.

**Comment by bdewater** [comment]
It seems that for some reason the revalidation message never arrived and this caused my PR to be stuck in the queue. Other PRs were observed to be merged in FIFO order.

**Comment by bdewater** [comment]
Not sure if I'm just terribly unlucky but after requeueing I noticed the behaviour again 🤔
