### ISSUE TITLE
Reject PRs with conflicts

### ISSUE THREAD

**Issue by lugray** [Shopify/shipit-engine#748]
If a PR in the merge queue has conflicts with master, it shouldn't sit there silently, it should be removed from the merge queue, and the author notified.

**Comment by byroot** [comment]
Conflict as in merge conflict?

**Comment by lugray** [comment]
Yes.

**Comment by byroot** [comment]
Closing as duplicate of: https://github.com/Shopify/shipit-engine/issues/749
