### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by PabloVallejo** [Shopify/shipit-engine#755]
Hi Folks, is there any interest in adding docker support, for an easy setup?

If so, I'm very interested in creating a PR with it.

**Comment by casperisfine** [comment]
What do you mean by Docker support? Publishing a docker image with Shipit setup inside?

**Comment by PabloVallejo** [comment]
@casperisfine as a first step I was thinking of adding both a `Dockerfile` and a `docker-compose.yml` files to the project;

**Comment by casperisfine** [comment]
That doesn't really answer my question.

Anyway, this repo is an engine, to setup Shipit you need to create a Rails app and mount the engine inside it. You can perfectly do all that from a 3rd party repo. If you end up with something that is easy to use for most people, then yeah we can talk about integrating it and make it the preferred way to deploy Shipit. 

But I'd rather see something fully functional before merging things.

**Comment by PabloVallejo** [comment]
@casperisfine you're totally right, I'm going to play a bit more with Shipit and find something functional for me before discussing it; 

Thanks!

**Comment by marc-barry** [comment]
Hey, we have taken a crack at Dockerizing Shipit in https://github.com/digitalocean/docker-shipit-engine. Images can be found under https://hub.docker.com/r/digitalocean/docker-shipit-engine. We are still in the early stages as we intend to run this on a Kubernetes cluster. It at least provides a base image that one can build upon by adding whatever is needed by your deployment system. For example, we need `kubectl`, `helm`, `go`, `ejson`, `make` and a few other dependancies for deployment.

@casperisfine If you have time we'd appreciate some comments on our approach. Either via an issue in the [repo](https://github.com/digitalocean/docker-shipit-engine) or a pull request.

**Comment by casperisfine** [comment]
Sure thing, I opened https://github.com/digitalocean/docker-shipit-engine/issues/3
