### ISSUE TITLE
Show variables and their values for a task that was run

### ISSUE THREAD

**Issue by fw42** [Shopify/shipit-engine#791]
When running many tasks with different parameters, we currently see only the name of the task from the shipit.yml, but we don't see the parameters.

<img width="664" alt="screen shot 2018-05-15 at 11 25 55" src="https://user-images.githubusercontent.com/2072686/40051564-17780230-5833-11e8-92b7-c5d562eea20d.png">

For example, each of those tasks has a `POD_ID` parameter. It would be nice if we could somehow see it's value in the UI.

We could maybe allow the title of the task to be templated? Like `"Failover a pod (POD_ID)" and then gsub the actual pod id into it. Or automatically show all variables and their values in the UI? That seems like the cleanest solution to me.

@byroot, thoughts?

@daniellaniyo, could you work on this? (unless Jean feels strongly and wants to do it himself).

**Comment by casperisfine** [comment]
> @daniellaniyo, could you work on this? (unless Jean feels strongly and wants to do it himself).

I have the time to do it if needed, but I don't absolutely want to do it and would be happy to let Daniella handle that. Ping me if you need any guidance.

**Comment by fw42** [comment]
Similar problem here:

<img width="561" alt="screen shot 2018-05-16 at 09 07 34" src="https://user-images.githubusercontent.com/2072686/40104556-977a8cc2-58e8-11e8-9a0c-18ea58a8369d.png">

Would be nice to be able to tell which one succeeded.

**Comment by casperisfine** [comment]
That one is not Shipit's responsability. it's sent by our chatbot in reaction of webhooks sent by Shipit. I think there is already all the data needed to do it.

**Comment by fw42** [comment]
> I have the time to do it if needed

Do you still have time to own this? Daniella is on vacation right now

**Comment by byroot** [comment]
Maybe later today, or worst case on Monday.

**Comment by fw42** [comment]
Monday is totally fine, thank you! ❤️
