### ISSUE TITLE
Kubernetes-Deploy Fails Citing Missing Rake

### ISSUE THREAD

**Issue by tebriel** [Shopify/shipit-engine#799]
Hi! I got `kubernetes-deploy` working locally, but when I run it with shipit, I get the following:
```
HEAD is now at 4a312f1... initial commit
$ kubernetes-deploy --max-watch-seconds 900 dd-monitor-load-test staging
pid: 49
Could not find rake-10.5.0 in any of the sources
Run `bundle install` to install missing gems.
kubernetes-deploy --max-watch-seconds 900 dd-monitor-load-test staging exited with status 7
```

However I can see that `rake` is present:
```
root@ca5c94123691:/opt/workdir# gem list | grep rake
rake (12.3.0, 10.5.0)
```

I'm guessing that `kubernetes-deploy` doesn't use rake, so I was figuring I've done something wrong setting up shipit-engine. 

shipit.load-test.yml
```
kubernetes:
  namespace: dd-monitor-load-test
  context: staging
```

Thanks for your help.

**Comment by casperisfine** [comment]
Hum, TBH I'm not that familiar with `kubernetes-deploy`.

@KnVerey @kirs does this error ring a bell for one of you?

**Comment by kirs** [comment]
Hmm, `kubernetes-deploy` is not using rake in any way as a direct dependency.

@tebriel I see that you've run `gem list | grep rake` from `root`, is Shipit running from root as well? Users may have different sets of gems installed.

> Could not find rake-10.5.0 in any of the sources
> Run `bundle install` to install missing gems.

This looks like to be coming from Bundler, which `kubernetes-deploy` is not loading either. Could that be because there's a Gemfile in a directory where `kubernetes-deploy` is running from?

**Comment by tebriel** [comment]
Hmmm, I was just thinking. The repo is nothing but a folder of .yml.erb and .yaml files, I wonder if Capistrano is trying to do something weird. We don’t use ruby, so I wasn’t expecting anything to do with rake either. I’ll throw some other files in there and make it look like a python project and see if that’s possibly it.

On Jun 1, 2018, at 5:29 AM, Kir Shatrov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, kubernetes-deploy is not using rake in any way as a direct dependency.

@tebriel<https://github.com/tebriel> I see that you've run gem list | grep rake from root, is Shipit running from root as well? Users may have different sets of gems installed.

Could not find rake-10.5.0 in any of the sources
Run bundle install to install missing gems.

This looks like to be coming from Bundler, which kubernetes-deploy is not loading either. Could that be because there's a Gemfile in a directory where kubernetes-deploy is running from?

**Comment by casperisfine** [comment]
Oh, you have a `Capfile`?

IIRC the `kubernetes` directive should shortcicuit all the other autodiscoveries, but I might be misremembering.

**Comment by casperisfine** [comment]
Nevermind. Looking at the output you posted, Shipit doesn't do anything during the `dependencies` step.

So it is indeed a ruby / rubygems issue.

I think Kir is on the right track here. The gem must be installed under the wrong user, so you do have access to the executable shim in your PATH, but then the gem can't be found.

I still don't get why it complains about rake though.

**Comment by tebriel** [comment]
so, as the user that sidekiq is running as, I tried this:
```
root@d24d26ac4ebb:/opt/workdir/data/stacks/ivr/custom-datadog/load-test/git# rake
(in /opt/workdir)
Run options: --seed 4500

# Running:



Finished in 0.000697s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

rake is available to that user, and works in the deploy directory (assuming I understand the way this works)

**Comment by byroot** [comment]
```
Finished in 0.000697s, 0.0000 runs/s, 0.0000 assertions/s.
```

That's a minitest output `o_0`.

What if you invoke `kubernetes-deploy` ? with `DEBUG=1` ?

Also not related, but I'd suggest moving away from running sidekiq as root.

**Comment by tebriel** [comment]
it runs fine when I manually call it (here's it without `DEBUG=1`):
```
[INFO][2018-06-01 15:36:01 +0000]
[INFO][2018-06-01 15:36:01 +0000]       ------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2018-06-01 15:36:01 +0000]       All required parameters and files are present
[INFO][2018-06-01 15:36:01 +0000]       Context staging found
[INFO][2018-06-01 15:36:01 +0000]       Namespace dd-monitor-load-test found
[INFO][2018-06-01 15:36:01 +0000]       Discovering templates:
[INFO][2018-06-01 15:36:01 +0000]         - ConfigMap/dd-monitor-configmap
[INFO][2018-06-01 15:36:01 +0000]         - Deployment/dd-monitor-agent
[INFO][2018-06-01 15:36:01 +0000]         - ConfigMap/postgres-config
[INFO][2018-06-01 15:36:01 +0000]
[INFO][2018-06-01 15:36:01 +0000]       ----------------------------Phase 2: Checking initial resource statuses-----------------------------
[INFO][2018-06-01 15:36:02 +0000]       ConfigMap/dd-monitor-configmap                    Available
[INFO][2018-06-01 15:36:02 +0000]       Deployment/dd-monitor-agent                       1 replica, 1 updatedReplica, 1 availableReplica
[INFO][2018-06-01 15:36:02 +0000]       ConfigMap/postgres-config                         Available
[INFO][2018-06-01 15:36:02 +0000]
[INFO][2018-06-01 15:36:02 +0000]       ----------------------Phase 3: Deploying kubernetes secrets from secrets.ejson----------------------
[INFO][2018-06-01 15:36:02 +0000]       Fetching ejson private key from secret ejson-keys
[INFO][2018-06-01 15:36:03 +0000]       Decrypting secrets.ejson
[INFO][2018-06-01 15:36:03 +0000]       Updating secret datadog-api-token
[INFO][2018-06-01 15:36:04 +0000]
[INFO][2018-06-01 15:36:04 +0000]       ------------------------------Phase 4: Predeploying priority resources------------------------------
[INFO][2018-06-01 15:36:04 +0000]       Deploying resources:
[INFO][2018-06-01 15:36:04 +0000]       - ConfigMap/dd-monitor-configmap (timeout: 30s)
[INFO][2018-06-01 15:36:04 +0000]       - ConfigMap/postgres-config (timeout: 30s)
[INFO][2018-06-01 15:36:04 +0000]       Successfully deployed in 0.5s: ConfigMap/dd-monitor-configmap, ConfigMap/postgres-config
[INFO][2018-06-01 15:36:04 +0000]
[INFO][2018-06-01 15:36:04 +0000]
[INFO][2018-06-01 15:36:04 +0000]       ----------------------------------Phase 5: Deploying all resources----------------------------------
[INFO][2018-06-01 15:36:04 +0000]       Deploying resources:
[INFO][2018-06-01 15:36:04 +0000]       - ConfigMap/dd-monitor-configmap (timeout: 30s)
[INFO][2018-06-01 15:36:04 +0000]       - Deployment/dd-monitor-agent (timeout: 420s)
[INFO][2018-06-01 15:36:04 +0000]       - ConfigMap/postgres-config (timeout: 30s)
[INFO][2018-06-01 15:36:05 +0000]       Successfully deployed in 0.9s: ConfigMap/dd-monitor-configmap, Deployment/dd-monitor-agent, ConfigMap/postgres-config
[INFO][2018-06-01 15:36:05 +0000]
[INFO][2018-06-01 15:36:05 +0000]       ------------------------------------------Result: SUCCESS-------------------------------------------
[INFO][2018-06-01 15:36:05 +0000]       Created/updated 1 secret and successfully deployed 3 resources
[INFO][2018-06-01 15:36:05 +0000]
[INFO][2018-06-01 15:36:05 +0000]       Successful resources
[INFO][2018-06-01 15:36:05 +0000]       ConfigMap/dd-monitor-configmap                    Available
[INFO][2018-06-01 15:36:05 +0000]       Deployment/dd-monitor-agent                       1 replica, 1 updatedReplica, 1 availableReplica
[INFO][2018-06-01 15:36:05 +0000]       ConfigMap/postgres-config                         Available
```

Additionally you're right, I had been a bit lazy, it now runs as a diff user. Still same problem (though we knew that wouldn't change it)

**Comment by byroot** [comment]
The only thing I can think of is inconsistent environment variables.

I'd suggest to print out the environment executed by shipit with:

```
deploy:
  pre:
    - env
```

And to compare it with the one you have when you manually exec h8s-deploy. It's possible some difference in RUBYLIB or RUBYPATH is causing this.
