### ISSUE TITLE
[Feature] Ability to order stack deploys by environment

### ISSUE THREAD

**Issue by sgringwe** [Shopify/shipit-engine#815]
We have both staging and production environments for our applications. We'd like to be able to enable Continuous deployment for both staging and production, but only deploy production after a successful staging deploy.

Would it be possible to add a feature to "tie" app environments together, such that we can tell shipit to wait to deploy production only after staging has been deployed successfully already. Even better would be to allow a configurable delay between staging/production pipeline deploys to let the deploy "bake" in staging first.

**Comment by byroot** [comment]
We actually recently implemented that in https://github.com/Shopify/shipit-engine/pull/813

It's not quite documented yet because it's subject to change, but we're been running in prod several weeks now, so It's very unlikely it will change significantly at this point.

**Comment by byroot** [comment]
Oh, and it's unreleased but you can use shipit-engine as a git gem.

**Comment by sgringwe** [comment]
@byroot amazing! do you have a rough idea of when the next release will be?

**Comment by byroot** [comment]
Not too long from now, I guess I could cut one Monday.

**Comment by casperisfine** [comment]
It's out https://rubygems.org/gems/shipit-engine/versions/0.25.0

**Comment by sgringwe** [comment]
I added some unofficial docs at https://github.com/Shopify/shipit-engine/wiki/Using-Release-Status-for-Chained-Continuous-Deployment, hopefully this is helpful.
