### ISSUE TITLE
Limit deploys to Tagged releases for rubygems

### ISSUE THREAD

**Issue by EiNSTeiN-** [Shopify/shipit-engine#83]
Like for Heroku, it would be simple enough to publish gems to rubygem using shipit2.

All we need is:
* Create a user for shipit2
* Install its API key on shipit2: `curl -u SHIPITUSER https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials; chmod 0600 ~/.gem/credentials`
* Add a rake task like this: https://github.com/Shopify/liquid/blob/c098235baa302fc9c09f675434206e290ce47119/Rakefile#L39
* The deploy command in shipit.yml would be: `rake build` and `rake release`

We need to make sure we cannot deploy the same version of a gem twice. I.e. there should ever be only one "version x.y.z" of a gem. If we want to deploy new commits, usually we need to make a new tag and release that tag.

So I was thinking for rubygems, it would be nice to have a feature to see only tags on the deploy page of shipit. Maybe configurable through shipit.yml or when the stack is created through the shipit2 interface.

@byroot comments?

**Comment by byroot** [comment]
We have this since more than a year and half. Closing.
