### ISSUE TITLE
Show who locked a commit

### ISSUE THREAD

**Issue by davidcornu** [Shopify/shipit-engine#860]
If you're looking at a stack page and see some locked commits, you can't tell who locked them.

This would be useful for

- Asking the person who locked the commit for more details
- Determining whether a commit was accidentally locked

----

The mechanism we use for `Stack` is pretty straightforward

https://github.com/Shopify/shipit-engine/blob/070da14b4f447f43f70377e095136edeea91af6f/test/dummy/db/schema.rb#L205

https://github.com/Shopify/shipit-engine/blob/070da14b4f447f43f70377e095136edeea91af6f/app/models/shipit/stack.rb#L369-L376

https://github.com/Shopify/shipit-engine/blob/070da14b4f447f43f70377e095136edeea91af6f/app/views/shipit/stacks/_banners.html.erb#L39

so we could likely do something similar for `Commit`.

**Comment by casperisfine** [comment]
Indeed. PR Welcome.

**Comment by davidcornu** [comment]
Implemented in #901
