### ISSUE TITLE
Webhook CSRF token authenticity

### ISSUE THREAD

**Issue by ixai** [Shopify/shipit-engine#871]
While trying to setup an instance of `shipit`, all webhooks sent by GitHub are being rejected because of a CSRF token authenticity issue (logs after the break).  Looking around, I found this commit 6c84ccfd7bf994953677149e12eb76a4a366617c that seems to enable CSRF validation for the `/webhooks` endpoint. I manually reverted that change and the hook was accepted. This is obviously not the correct way to do this, could you help me understand how to work around CSRF for webhooks?

```
I, [2019-02-13T20:27:14.366776 #8]  INFO -- : [235792a3-5e6f-4c2a-98a4-52f0836694da] Started POST "/webhooks" for 192.30.252.35 at 2019-02-13 20:27:14 +0000
I, [2019-02-13T20:27:14.370870 #8]  INFO -- : [235792a3-5e6f-4c2a-98a4-52f0836694da] Processing by Shipit::WebhooksController#create as */*
I, [2019-02-13T20:27:14.380176 #8]  INFO -- : [235792a3-5e6f-4c2a-98a4-52f0836694da]   Parameters: {"number"=>2, "pull_request"=>{...}}
W, [2019-02-13T20:27:14.380971 #8]  WARN -- : [235792a3-5e6f-4c2a-98a4-52f0836694da] Can't verify CSRF token authenticity.
I, [2019-02-13T20:27:14.381261 #8]  INFO -- : [235792a3-5e6f-4c2a-98a4-52f0836694da] Completed 422 Unprocessable Entity in 1ms
F, [2019-02-13T20:27:14.382093 #8] FATAL -- : [235792a3-5e6f-4c2a-98a4-52f0836694da]
F, [2019-02-13T20:27:14.382134 #8] FATAL -- : [235792a3-5e6f-4c2a-98a4-52f0836694da] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
F, [2019-02-13T20:27:14.382161 #8] FATAL -- : [235792a3-5e6f-4c2a-98a4-52f0836694da]
F, [2019-02-13T20:27:14.382201 #8] FATAL -- : [235792a3-5e6f-4c2a-98a4-52f0836694da] actionpack (5.2.2) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
```

**Comment by byroot** [comment]
Thanks for the report. [Someone else noticed it too recently](https://github.com/Shopify/shipit-engine/commit/664cf64bd9bb3f4b67f7a37026d6de214643c652#r32123364) cc @celsodantas.

I'll try to figure out why it was breaking our install and revert that commit.

**Comment by casperisfine** [comment]
Reverted in https://github.com/Shopify/shipit-engine/commit/f094487f1e4e752552389ebadf240fdc124cb667 and improved in https://github.com/Shopify/shipit-engine/commit/3a3a136c610a4f758ccc32526cc7c615c4db2507

I'll release a new version in a bit.

**Comment by ixai** [comment]
Thank you!
