### ISSUE TITLE
No new commit shows up after a commit without a message

### ISSUE THREAD

**Issue by oodiete** [Shopify/shipit-engine#872]
To recreate, make a commit without a commit message: 

`git commit --allow-empty-message -m ""`
`git push`

This commit would not show up on shipit and all additional commits to that repo would also not show up. The bug is caused by stripping a null.  [See stacktrace on gist](https://gist.github.com/oodiete/3b06f17e19fb3e008f2e1b12dcfad614)

**Comment by byroot** [comment]
Thanks for the report. That should be a simple enough fix. I'll handle it on Monday unless you feel like submitting a PR before then.

The failing line is likely this one: https://github.com/Shopify/shipit-engine/blob/f5f12a007caaae7f052a2dd626fbc5bc732f135a/app/models/shipit/commit.rb#L201
