### ISSUE TITLE
Monorepo Best Practices

### ISSUE THREAD

**Issue by bspellio** [Shopify/shipit-engine#875]
Does shipit currently have any best practices for handling mono-repos?

Currently, we have a repository that has three related, yet decoupled services that all have separate app servers & data-stores and it's not entirely clear if there's a defined way to handle this with shipit.

**Comment by casperisfine** [comment]
Depends on your requirements.

If they can be deployed out of order then [`machine.directory`](https://github.com/shopify/shipit-engine#directory) and multiple stacks should do the trick.

**Comment by bspellio** [comment]
`machine.directory` looks like the right idea! Our primary requirement is that we'd like to _not_ have to redeploy all of our services if they don't change, so multiple stacks makes sense.

Suppose I have the directory structure:
```
monorepo-name/
  rails-app1/
    bin/
  rails-app2/
    bin/
```

In this case, how would one specify multiple stacks per repo via `shipit.yml`? Would they live within each app directory (e.g. `rails-app1` & `rails-app2`?

**Comment by casperisfine** [comment]
> Would each `shipit.yml` file live within each app directory

Unfortunately no, that isn't supported today.

All ymls have to be at the toplevel, so:

```
monorepo-name/
  shipit.app1.yml
  rails-app1/
  shipit.app2.yml
  rails-app2/
```

Then the `app1` / `app2` have to map with the `environment` attribute on the stack.

> Our primary requirement is that we'd like to _not_ have to redeploy all of our services if they don't change

That however isn't really supported by Shipit. It can't ignore commits that don't concern your subdirectory. However your deploy script knows what range is deployed and has git history, so you could noop the deploy if the range doesn't contain any relevant change.

But that a quite opiniated feature so it's better handled by deploy scripts than by shipit itself.

**Comment by bspellio** [comment]
Makes sense! Thanks for the help @casperisfine. I'll close this out.
