### ISSUE TITLE
Better handle Redis connection error in PerformTaskJob

### ISSUE THREAD

**Issue by casperisfine** [Shopify/shipit-engine#876]
### Context

Tasks being performed regularly update a key in Redis: https://github.com/Shopify/shipit-engine/blob/36e3cf096837d9fb8b2d01046f4be321f6b61e96/app/models/shipit/task.rb#L241-L247

The idea is that if the job was hard killed, the rest of the app can notice it once the key starts to get old and take action.

However if there's a Redis blip (e.g. a short service disruption on the service instance) setting the key would fail and bring the job down.

It would be much better to have some error handling here:

```
Redis::CannotConnectError: Error connecting to Redis on redis-xxxx.shipit-production:6379 (Redis::TimeoutError)
    gems/redis-3.3.5/lib/redis/client.rb:345:in `rescue in establish_connection'
    gems/redis-3.3.5/lib/redis/client.rb:330:in `establish_connection'
    ...
    gems/shipit-engine-f5f12a007caa/app/models/shipit/task.rb:242:in `ping'
    gems/shipit-engine-f5f12a007caa/app/jobs/shipit/perform_task_job.rb:78:in `block in capture!'
```

It probably should still give up after Redis is not responding for too long, but it should properly mark the task as failed in the same time so that it doesn't stay as running for too long.

**Comment by esnunes** [comment]
Closed by #899
