### ISSUE TITLE
Dark mode: Save On-Call's from middle of the night torture

### ISSUE THREAD

**Issue by sorryeh** [Shopify/shipit-engine#878]
Dark mode: Save On-Call's from middle of the night torture

Plz have a toggle to have a dark mode for the shipit page :)

**Comment by paulanunda** [comment]
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US does a good job of enabling dark mode on the vast majority of sites.
