### ISSUE TITLE
GitHub status page API is broken

### ISSUE THREAD

**Issue by casperisfine** [Shopify/shipit-engine#881]
We record the GitHub status in https://github.com/Shopify/shipit-engine/blob/f2f6dbb672f3a5073d46e5353509705b25e55ec5/app/models/shipit/github_status.rb and use it to display a warning when there is an incident on GitHub.

It seems that they recently migrated from their in house solution to statuspage.io, so the API no longer exist.

We can either refactor the code to use statuspage.io's API at https://www.githubstatus.com/api/v2/summary.json

Or simply strip all that code.

cc @Shopify/pipeline

**Comment by sciyoshi** [comment]
See also https://github.com/octokit/octokit.rb/issues/1107

**Comment by ohsabry** [comment]
This was a big gotcha for us, and we had to make a rakefile with a commented out `Shipit::GithubStatus.refresh_status` to run shipit: 
https://github.com/TouchBistro/docker-shipit-engine/blob/master/lib/tasks/cronfix.rake#L6


Have you guys decided whether you want to switch to statuspage or to remove this code? we are running shipit here at our shop and would be happy to contribute with a PR

cc @itsWill sup

**Comment by solojavier** [comment]
@peerkleio @casperisfine Since #928 is merged, I believe this issues can be marked as closed.
