### ISSUE TITLE
Can you create a new 0.27.1 or newer release?

### ISSUE THREAD

**Issue by marc-barry** [Shopify/shipit-engine#884]
@byroot The latest gem release is https://rubygems.org/gems/shipit-engine/versions/0.27.0. I'm working on containerizing `shipit-engine` so we can deploy it with Kubernetes. Would you be able to release a new Gem version so I can use this for the container image? I ran into #871 as a result of https://github.com/Shopify/shipit-engine/commit/6c84ccfd7bf994953677149e12eb76a4a366617c in the current `0.27.0` version and need to pick up a release with https://github.com/Shopify/shipit-engine/commit/f094487f1e4e752552389ebadf240fdc124cb667 and https://github.com/Shopify/shipit-engine/commit/3a3a136c610a4f758ccc32526cc7c615c4db2507.

**Comment by casperisfine** [comment]
Turns out I did cut the release over a month ago, but forgot to hit the deploy button: https://github.com/Shopify/shipit-engine/commit/f5f12a007caaae7f052a2dd626fbc5bc732f135a

-_-

It's published now.

**Comment by marc-barry** [comment]
🎉 https://rubygems.org/gems/shipit-engine/versions/0.27.1. Thank you.
