### ISSUE TITLE
it does not appear possible to use secrets with hooks

### ISSUE THREAD

**Issue by npaufler** [Shopify/shipit-engine#919]
The database schema for hooks has a `secret` field which I'd assume is intended for allowing you to authenticate hook submissions on your webhook listener.

I've inserted some hook records to test and I receive them, but the contents of the `secret` field do not appear to be set anywhere - it's not being passed as part of the URL, it's not being added in the headers (i.e. X-Shipit-Secret or something), and I don't see it anywhere in the JSON payload either.

If I'm reading https://github.com/Shopify/shipit-engine/blob/9052291a4aa9da5d37ff86d54549f21921596718/app/serializers/shipit/hook_serializer.rb correctly it doesn't look like the `secret` field is even being read.

Is this behavior actually supposed to be implemented or is it incomplete as of today?

Thanks!

**Comment by casperisfine** [comment]
Nice catch. I probably meant to replicate GitHub's signed webhook feature but simply forgot about it.
