### ISSUE TITLE
Can you create a new release?

### ISSUE THREAD

**Issue by marc-barry** [Shopify/shipit-engine#921]
We want to update https://github.com/digitalocean/docker-shipit-engine with some changes that have been merged since https://github.com/Shopify/shipit-engine/releases/tag/v0.27.1 and https://rubygems.org/gems/shipit-engine/versions/0.27.1 were created. Can you cut a new release in GitHub?

Let me know if there is a better way to request this. I'm trying to avoid us forking the repo :).

**Comment by casperisfine** [comment]
Done. 0.28 is out.



> Let me know if there is a better way to request this.

It's fine. We should release more often without anyone requesting it.

**Comment by marc-barry** [comment]
> Done. 0.28 is out.

Thanks!

**Comment by ohsabry** [comment]
@casperisfine didn't want to make a new issue - can you cut a new release soon-ish when you get some time? I want to update shipit and I'd like to have some of the features currently in master - we build it in a way similar to DO with github releases

**Comment by casperisfine** [comment]
@ohsabry done: https://rubygems.org/gems/shipit-engine/versions/0.30.0
