### ISSUE TITLE
Shipit-created branches being pushed to deployed repo

### ISSUE THREAD

**Issue by davefp** [Shopify/shipit-engine#955]
We recently updated our Shipit install from v0.28.0 to v0.28.1, and now we're seeing new branches being pushed back to the GitHub repos we're deploying.

They're named `shipit-deploy/production` and `shipit-deploy/staging` which match the stack names we have.

This is unexpected and problematic as it triggers CI runs. We've configured around it for now but a fix (or explanation if this is intentional) would be appreciated.

My only idea so far is that it has to do with the branch name config that was changed in #927.

**Comment by ohsabry** [comment]
We just noticed this as well after upgrading - it is still there on current master version of shipit-engine. @davefp Have you found a workaround via shipit itself or its configuration, or did you stop those branches from triggering CI runs?

**Comment by casperisfine** [comment]
@davefp apologies, I usually answer all issues, but I somehow missed this one.

This feature was added in https://github.com/Shopify/shipit-engine/pull/917, I asked for it to be opt-in but seems like it was missed.

**Comment by casperisfine** [comment]
I made it opt-in in `da9477a`, so the next time you update Shipit it should stop updating that branch.
