### ISSUE TITLE
Merge Queue v2 in shipit-engine?

### ISSUE THREAD

**Issue by jonasoberschweiber** [Shopify/shipit-engine#956]
I just saw your latest post on the [next generation merge queue](https://engineering.shopify.com/blogs/engineering/successfully-merging-work-1000-developers) and was wondering if this is something that will eventually land in shipit-engine or if it's a separate, internal tool that you've developed. We're especially interested in the comment-based interface.

**Comment by casperisfine** [comment]
cc @DazWorrall @wvanbergen

**Comment by wvanbergen** [comment]
We decided to implement the new merge queue as part of a new code base, for several reasons.

1. The GitHub GraphQL API makes implementing a merge & deployment tool a lot simpler than the approach shipit had to take, which involves a complex synchronizing mechanism with webhooks. 
2. Some of the assumptions that shipit makes (e.g. you always deploy the same branch) are no longer true in our new merge and deploy model.

This would mean almost a complete rewrite, and starting over was simpler. We are considering open sourcing it. Right now we are in a weird spot where we use the new shipit for merging, and the old shipit for deploying and have some bespoke ways for the two tools to work together. So right now is not the best time to open source our work, but maybe in 6 months are so it is more feasible.

**Comment by jonasoberschweiber** [comment]
Thank you for the quick reply!

**Comment by bpaquet** [comment]
> We decided to implement the new merge queue as part of a new code base, for several reasons.
> 
> 1. The GitHub GraphQL API makes implementing a merge & deployment tool a lot simpler than the approach shipit had to take, which involves a complex synchronizing mechanism with webhooks.
> 2. Some of the assumptions that shipit makes (e.g. you always deploy the same branch) are no longer true in our new merge and deploy model.
> 
> This would mean almost a complete rewrite, and starting over was simpler. We are considering open sourcing it. Right now we are in a weird spot where we use the new shipit for merging, and the old shipit for deploying and have some bespoke ways for the two tools to work together. So right now is not the best time to open source our work, but maybe in 6 months are so it is more feasible.

Hello @wvanbergen, any news 6 months laters? :)

Thx

**Comment by wvanbergen** [comment]
No news - we are still actively working on this. While we are using it in production, the product is still seeing too many changes to open source it at this point. It's still on the radar though.

**Comment by bootstraponline** [comment]
@wvanbergen Is there an update on open sourcing the merge queue v2 project? 🙂

**Comment by wvanbergen** [comment]
Nothing to announce at this point. We are still actively working on the new version of shipit. While we already use it in production at Shopify, it is still rapidly changing based on what we learn. We decided to postpone open sourcing until it is more stable.

**Comment by bootstraponline** [comment]
I think an unstable release may be helpful for companies looking at building their own similar merge queue. I'm looking forward the the release.

**Comment by angeliski** [comment]
Hey, @wvanbergen Any news about that? I could help if needed
Cheers

**Comment by benlangfeld** [comment]
I think it's more than clear that the new version will not be released open-source like shipit-engine.
