### ISSUE TITLE
Shipit should set an in_progress deployment status

### ISSUE THREAD

**Issue by DazWorrall** [Shopify/shipit-engine#958]
Shipit creates a deployment as soon as the task starts, but seems to only set the deployment status when the task is complete:

<img width="474" alt="Screenshot 2019-11-27 at 11 33 50" src="https://user-images.githubusercontent.com/398706/69720122-d25e6180-1109-11ea-99e7-5d1d2075e5ad.png">

=> 

<img width="545" alt="Screenshot 2019-11-27 at 11 36 24" src="https://user-images.githubusercontent.com/398706/69720277-26694600-110a-11ea-9021-133de7d4b41c.png">

This means other apps cannot discover the log url of the in flight deploy. Shipit should set an [`in_progress`](https://developer.github.com/v3/repos/deployments/#create-a-deployment-status) status after creating the deployment.

**Comment by ajshepley** [comment]
(Tracking purposes)

This should be resolved by https://github.com/Shopify/shipit-engine/pull/959

**Comment by DazWorrall** [comment]
Fixed in #959
