### ISSUE TITLE
twine: not found error while trying to deploy.

### ISSUE THREAD

**Issue by tanema** [Shopify/shipit-engine#992]
Hello! I am trying to deploy https://github.com/Shopify/pyactiveresource

It seems that shipit has auto detection on for pypi here https://github.com/Shopify/shipit-engine/blob/f8d390722ee7dcb5c185e2e97695fa2897b218ad/app/models/shipit/deploy_spec/pypi_discovery.rb 

It works and tries to do all the steps however it seems like twine is not installed properly.

Failed Deploy: https://shipit.shopify.io/shopify/pyactiveresource/pypi/deploys/910745

```
$ twine upload dist/*
pid: 451004
sh: 1: twine: not found
twine upload dist/* terminated with exit status 127
```

I am not a python expert so I cant really help with why this is.

**Comment by casperisfine** [comment]
@tanema you probably meant to open this issue on the internal repo: https://github.com/Shopify/shipit.

**Comment by tanema** [comment]
@casperisfine But the autodetection is within the engine? I will open the issue there but it seems like the bug is here

**Comment by casperisfine** [comment]
It is, but Shipit autodetections simply scan the deployed rpeo to figure how it should be deployed.

It's the responsability of the shipit installation to have the required tools properly installed. Not shipit-engine.
